FROM {{ tesseract_ocr_runtime_base_image }}

WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      poppler-utils \
      tesseract-ocr \
{% for package in tesseract_ocr_runtime_language_packages %}
      tesseract-ocr-{{ package }} \
{% endfor %}
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY tesseract_ocr_service.py ./tesseract_ocr_service.py
