from typing import Any

class Client:
    async def connect(self, **kwargs: Any) -> None: ...
    async def publish(self, subject: str, payload: bytes) -> None: ...
    async def flush(self, *, timeout: float) -> None: ...
    async def drain(self) -> None: ...
