---
mattermost_database_name: mattermost
mattermost_database_user: mattermost_admin
mattermost_database_support_role: mattermost_user
mattermost_postgres_secret_dir: /etc/lv3/mattermost
mattermost_postgres_password_file: "{{ mattermost_postgres_secret_dir }}/database-password"
mattermost_local_artifact_dir: "{{ repo_shared_local_root }}/mattermost"
mattermost_database_password_local_file: "{{ repo_shared_local_root }}/mattermost/database-password.txt"
