---
netbox_database_name: netbox
netbox_database_user: netbox
netbox_postgres_secret_dir: /etc/lv3/netbox
netbox_postgres_password_file: "{{ netbox_postgres_secret_dir }}/database-password"
netbox_local_artifact_dir: "{{ repo_shared_local_root }}/netbox"
netbox_database_password_local_file: "{{ repo_shared_local_root }}/netbox/database-password.txt"
