---
gitea_database_name: gitea
gitea_database_user: gitea
gitea_postgres_password_file: "{{ gitea_postgres_secret_dir }}/database-password"
gitea_database_password_local_file: "{{ gitea_local_artifact_dir }}/database-password.txt"
