---
flowinquiry_service_topology: "{{ hostvars[platform_topology_host].platform_service_topology | service_topology_get('flowinquiry') }}"
flowinquiry_public_base_url: "https://{{ flowinquiry_service_topology.public_hostname }}"
flowinquiry_image: ghcr.io/flowinquiry/flowinquiry-server:latest
flowinquiry_db_image: postgres:16-alpine
flowinquiry_db_password_local_file: "{{ flowinquiry_local_artifact_dir }}/db-password.txt"
flowinquiry_db_password_remote_file: "{{ flowinquiry_secret_dir }}/db-password.txt"
