#!/usr/bin/env python3
"""ADR query tool for the proxmox_florin_server repo.

USE THIS TOOL when you need to find, read, or query Architecture Decision Records.
Do not manually grep through docs/adr/ — use this tool instead.

ADRs live in docs/adr/ as markdown files named NNNN-slug.md (e.g. 0153-distributed-resource-lock-registry.md).
There are 290+ ADRs covering every platform decision. Each file starts with a metadata block:

  - Status: Accepted | Proposed | Superseded | Deprecated
  - Implementation Status: Implemented | Partial | Not Implemented | Deprecated
  - Implemented In Repo Version: X.Y.Z
  - Implemented In Platform Version: X.Y.Z
  - Implemented On: YYYY-MM-DD
  - Date: YYYY-MM-DD

A pre-built index is available at docs/adr/.index.yaml (generated by scripts/generate_adr_index.py).
This tool uses the index for fast list/status-summary operations and falls back to direct file parsing
for search and show operations.

COMMANDS
--------
list            List all ADRs, optionally filtered by status.
show            Display one ADR by number or slug.
search          Full-text search across ADR content.
affecting       Find ADRs that mention a specific resource or identifier.
status-summary  Count ADRs by status.

EXAMPLES
--------
  python3 scripts/adr_query_tool.py list
  python3 scripts/adr_query_tool.py list --status accepted --limit 20
  python3 scripts/adr_query_tool.py show 153
  python3 scripts/adr_query_tool.py show distributed-resource-lock-registry
  python3 scripts/adr_query_tool.py search "maintenance window"
  python3 scripts/adr_query_tool.py search "vm:120"
  python3 scripts/adr_query_tool.py affecting "vm:120"
  python3 scripts/adr_query_tool.py affecting "docker-runtime-lv3"
  python3 scripts/adr_query_tool.py affecting "postgres"
  python3 scripts/adr_query_tool.py status-summary
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
ADR_DIR = REPO_ROOT / "docs" / "adr"
INDEX_FILE = ADR_DIR / ".index.yaml"

# Regex patterns for parsing ADR front-matter (first ~20 lines)
_RE_STATUS = re.compile(r"^-\s+Status:\s+(.+)$", re.IGNORECASE)
_RE_IMPL_STATUS = re.compile(r"^-\s+Implementation Status:\s+(.+)$", re.IGNORECASE)
_RE_DATE = re.compile(r"^-\s+Date:\s+(.+)$", re.IGNORECASE)
_RE_IMPL_ON = re.compile(r"^-\s+Implemented On:\s+(.+)$", re.IGNORECASE)
_RE_TITLE = re.compile(r"^#\s+ADR\s+\d+[:\s]+(.+)$")


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------

def _adr_files() -> list[Path]:
    """Return all ADR markdown files sorted by number."""
    return sorted(
        fp for fp in ADR_DIR.glob("*.md")
        if fp.name[0].isdigit()
    )


def _parse_number(fp: Path) -> int:
    try:
        return int(fp.name[:4])
    except ValueError:
        return 0


def _parse_slug(fp: Path) -> str:
    stem = fp.stem  # e.g. "0153-distributed-resource-lock-registry"
    if "-" in stem:
        return stem[stem.index("-") + 1:]
    return stem


def _read_text(fp: Path) -> str:
    try:
        return fp.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def _parse_meta(fp: Path) -> dict:
    """Extract metadata from the first 25 lines of an ADR file."""
    text = _read_text(fp)
    lines = text.splitlines()[:25]

    title = ""
    status = ""
    impl_status = ""
    date = ""

    for line in lines:
        if not title:
            m = _RE_TITLE.match(line.strip())
            if m:
                title = m.group(1).strip()
        if not status:
            m = _RE_STATUS.match(line.strip())
            if m:
                status = m.group(1).strip()
        if not impl_status:
            m = _RE_IMPL_STATUS.match(line.strip())
            if m:
                impl_status = m.group(1).strip()
        if not date:
            m = _RE_DATE.match(line.strip())
            if m:
                date = m.group(1).strip()
            elif not date:
                m2 = _RE_IMPL_ON.match(line.strip())
                if m2:
                    date = m2.group(1).strip()

    return {
        "number": _parse_number(fp),
        "slug": _parse_slug(fp),
        "title": title or fp.stem,
        "status": status,
        "implementation_status": impl_status,
        "date": date,
    }


def _snippet(text: str, query: str, max_len: int = 200) -> str:
    lower = text.lower()
    idx = lower.find(query.lower())
    if idx == -1:
        return text[:max_len]
    start = max(0, idx - 60)
    end = min(len(text), idx + len(query) + 140)
    fragment = text[start:end]
    if start > 0:
        fragment = "..." + fragment
    if end < len(text):
        fragment = fragment + "..."
    return fragment


def _find_adr_file(number_or_slug: str) -> Path | None:
    """Resolve a number (int or string) or slug to an ADR Path."""
    # Try numeric match
    try:
        num = int(number_or_slug)
        prefix = f"{num:04d}-"
        for fp in ADR_DIR.glob(f"{prefix}*.md"):
            return fp
    except ValueError:
        pass

    # Try exact slug match or substring slug match
    slug_lower = number_or_slug.lower()
    for fp in _adr_files():
        if _parse_slug(fp).lower() == slug_lower:
            return fp
    for fp in _adr_files():
        if slug_lower in _parse_slug(fp).lower():
            return fp
    return None


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def command_list(args) -> int:
    status_filter: str | None = args.status.lower() if args.status else None
    limit: int | None = args.limit

    results = []
    for fp in _adr_files():
        meta = _parse_meta(fp)
        if status_filter and meta["status"].lower() != status_filter:
            continue
        results.append(meta)

    if limit:
        results = results[:limit]

    if not results:
        print(json.dumps([]))
        return 2

    print(json.dumps(results, indent=2))
    return 0


def command_show(args) -> int:
    target: str = args.number_or_slug
    fp = _find_adr_file(target)
    if fp is None:
        print(
            json.dumps({"error": f"ADR not found: {target}", "type": "FileNotFoundError"}),
            file=sys.stderr,
        )
        return 1

    meta = _parse_meta(fp)
    meta["content_markdown"] = _read_text(fp)
    print(json.dumps(meta, indent=2))
    return 0


def command_search(args) -> int:
    query: str = args.query
    limit: int = args.limit
    query_lower = query.lower()

    scored = []
    for fp in _adr_files():
        content = _read_text(fp)
        count = content.lower().count(query_lower)
        if count == 0:
            continue
        meta = _parse_meta(fp)
        scored.append({
            "number": meta["number"],
            "title": meta["title"],
            "snippet": _snippet(content, query),
            "relevance": count,
        })

    scored.sort(key=lambda r: r["relevance"], reverse=True)
    scored = scored[:limit]

    if not scored:
        print(json.dumps([]))
        return 2

    print(json.dumps(scored, indent=2))
    return 0


def command_affecting(args) -> int:
    resource: str = args.resource
    limit: int = args.limit
    resource_lower = resource.lower()

    results = []
    for fp in _adr_files():
        content = _read_text(fp)
        count = content.lower().count(resource_lower)
        if count == 0:
            continue
        meta = _parse_meta(fp)
        results.append({
            "number": meta["number"],
            "title": meta["title"],
            "snippet": _snippet(content, resource),
            "relevance": count,
        })

    results.sort(key=lambda r: r["relevance"], reverse=True)
    results = results[:limit]

    if not results:
        print(json.dumps([]))
        return 2

    print(json.dumps(results, indent=2))
    return 0


def command_status_summary(args) -> int:  # noqa: ARG001
    by_status: dict[str, int] = {}
    total = 0

    for fp in _adr_files():
        meta = _parse_meta(fp)
        s = meta["status"] or "Unknown"
        by_status[s] = by_status.get(s, 0) + 1
        total += 1

    result = {
        "total": total,
        "by_status": dict(sorted(by_status.items(), key=lambda kv: kv[1], reverse=True)),
    }
    print(json.dumps(result, indent=2))
    return 0


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Query the ADR library in the proxmox_florin_server repo.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # list
    p_list = subparsers.add_parser("list", help="List all ADRs, optionally filtered by status.")
    p_list.add_argument(
        "--status",
        help="Filter by status (case-insensitive): accepted, proposed, superseded, deprecated, implemented.",
    )
    p_list.add_argument("--limit", type=int, help="Maximum number of results to return.")
    p_list.set_defaults(func=command_list)

    # show
    p_show = subparsers.add_parser("show", help="Display one ADR by number or slug.")
    p_show.add_argument("number_or_slug", help="ADR number (e.g. 153) or slug (e.g. distributed-resource-lock-registry).")
    p_show.set_defaults(func=command_show)

    # search
    p_search = subparsers.add_parser("search", help="Full-text search across all ADR content.")
    p_search.add_argument("query", help="Search query string (case-insensitive substring match).")
    p_search.add_argument("--limit", type=int, default=10, help="Maximum number of results (default: 10).")
    p_search.set_defaults(func=command_search)

    # affecting
    p_affecting = subparsers.add_parser("affecting", help="Find ADRs that mention a specific resource.")
    p_affecting.add_argument("resource", help="Resource identifier to search for, e.g. 'vm:120', 'postgres', 'docker-runtime-lv3'.")
    p_affecting.add_argument("--limit", type=int, default=20, help="Maximum number of results (default: 20).")
    p_affecting.set_defaults(func=command_affecting)

    # status-summary
    p_status = subparsers.add_parser("status-summary", help="Count ADRs by status.")
    p_status.set_defaults(func=command_status_summary)

    return parser


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> int:
    args = build_parser().parse_args()
    try:
        return args.func(args)
    except SystemExit:
        raise
    except Exception as exc:
        print(json.dumps({"error": str(exc), "type": type(exc).__name__}), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
