#!/usr/bin/env python3
"""Emergency credential rotation after public repository exposure.

ADR 0405 — Regenerate all platform-generated credentials so that values
recoverable from public git history become useless.

Usage:
    # List all secrets that will be rotated (dry run):
    python scripts/emergency_credential_rotation.py --list

    # Preview what will be regenerated for a specific tier:
    python scripts/emergency_credential_rotation.py --tier t1 --plan

    # Rotate a specific tier:
    python scripts/emergency_credential_rotation.py --tier t1 --apply

    # Rotate everything:
    python scripts/emergency_credential_rotation.py --tier all --apply

    # Rotate a single secret by ID:
    python scripts/emergency_credential_rotation.py --secret keycloak_grafana_client_secret --apply
"""

from __future__ import annotations

import argparse
import base64
import datetime as dt
import json
import os
import secrets
import string
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(os.environ.get("ROTATION_REPO_ROOT", Path(__file__).resolve().parent.parent))
SECRETS_MANIFEST = REPO_ROOT / "config" / "controller-local-secrets.json"
RECEIPT_DIR = REPO_ROOT / "receipts" / "credential-rotations"

# ADR 0403: Safe password alphabet — no characters that break shell, YAML,
# Jinja2, URL encoding, or PostgreSQL connection strings.
SAFE_ALPHABET = string.ascii_letters + string.digits + "-_"

# Tier classification based on privilege level and exposure risk.
TIER_DEFINITIONS = {
    "t1": {
        "label": "CRITICAL — directly exposed credentials",
        "secret_ids": [
            "semaphore_admin_password",
            "semaphore_database_password",
            "semaphore_api_token",
        ],
    },
    "t2": {
        "label": "HIGH — privileged infrastructure credentials",
        "secret_id_prefixes": [
            "keycloak_",
            "openbao_",
            "bootstrap_ssh_",
            "control_plane_recovery_",
            "backup_vm_",
            "proxmox_api_",
            "step_ca_",
        ],
    },
    "t3": {
        "label": "STANDARD — all remaining platform-generated secrets",
        "description": "Everything with origin=generated_by_repo not in T1 or T2",
    },
    "ext": {
        "label": "EXTERNAL — self-hosted service tokens (previously 'provided_externally')",
        "description": "Tokens for self-hosted services that were originally set up manually",
    },
}

# Env-var secrets that are self-hosted and can be rotated locally.
# Maps secret_id -> file path under ~/.config/codex-secrets/ for persistence.
ENV_SECRET_LOCAL_PATHS = {
    "hetzner_dns_api_token": Path.home() / ".config" / "codex-secrets" / "hetzner_dns_api_token",
    "tailscale_api_key": Path.home() / ".config" / "codex-secrets" / "tailscale_api_key",
    "ansible_galaxy_server_token": Path.home() / ".config" / "codex-secrets" / "ansible_galaxy_server_token",
    "mattermost_webhook_url": Path.home() / ".config" / "codex-secrets" / "mattermost_webhook_url",
    "proxmox_backup_cifs_password": Path.home() / ".config" / "codex-secrets" / "proxmox_backup_cifs_password",
    "proxmox_dr_offsite_password": Path.home() / ".config" / "codex-secrets" / "proxmox_dr_offsite_password",
}

# Env-var secrets that are NOT rotatable (hostnames, commands, identifiers).
ENV_NOT_SECRETS = {
    "tailscale_tailnet",
    "tailscale_invite_endpoint",
    "proxmox_backup_cifs_server",
    "proxmox_backup_cifs_share",
    "proxmox_backup_cifs_username",
    "step_ca_ssh_register_command",
    "step_ca_ssh_revoke_command",
}

# Secrets that need special handling (not a simple text file replacement).
SPECIAL_HANDLERS = {
    # SSH keys need key generation, not random strings
    "bootstrap_ssh_private_key": "ssh_ed25519",
    "control_plane_recovery_runtime_ssh_private_key": "ssh_ed25519",
    "coolify_server_ssh_private_key": "ssh_ed25519",
    # RSA keys
    "lago_rsa_private_key": "rsa_2048",
    # Nomad TLS keys
    "nomad_tls_ca_key": "skip",  # requires cfssl or step-ca regeneration
    "nomad_tls_client_key": "skip",
    "nomad_tls_server_key": "skip",
    # Cosign keys
    "gitea_release_bundle_cosign_private_key": "skip",  # requires cosign keygen
    # JSON payloads (not simple text secrets)
    "backup_vm_api_token_payload": "skip",  # regenerated by Proxmox role
    "proxmox_api_token_payload": "skip",  # regenerated by Proxmox role
    "proxmox_ops_pam_totp_state": "skip",  # regenerated by TFA setup
    "coolify_admin_auth": "json_password",
    "semaphore_admin_auth": "json_password",
    "woodpecker_admin_auth": "json_password",
    "woodpecker_bootstrap_spec": "skip",  # complex JSON, reconverge regenerates
    "portainer_admin_auth": "json_password",
    "plane_admin_auth": "json_password",
    "harbor_check_runner_robot_secret": "skip",  # regenerated by Harbor role
    "flagsmith_environment_keys": "skip",  # regenerated by Flagsmith role
    "lago_producer_catalog": "skip",  # regenerated by Lago role
    "mattermost_incoming_webhooks": "skip",  # regenerated by Mattermost
    "uptime_kuma_admin_session": "skip",  # session cookie, not a credential
    "control_plane_recovery_controller_bundle": "skip",  # regenerated by role
    # Init payload for OpenBao — contains unseal keys, MUST be handled manually
    "openbao_init_payload": "skip",
    # Cosign password — separate from key
    "gitea_release_bundle_cosign_password": "text",
    # GlitchTip DSNs — contain URLs with embedded tokens
    "glitchtip_mail_gateway_dsn": "skip",  # regenerated by GlitchTip role
    "glitchtip_platform_findings_event_url": "skip",
    "glitchtip_windmill_jobs_dsn": "skip",
    # Matrix signing key — special format
    "matrix_synapse_signing_key": "skip",  # regenerated by Matrix role
    # Provider env files
    "serverclaw_provider_env": "skip",  # complex env file, manual
    # Argon2 hash derived from admin token
    "vaultwarden_admin_token_hash": "skip",  # derived from vaultwarden_admin_token
    # Public key derived from private
    "coolify_server_ssh_public_key": "skip",  # derived from private key
}


def load_manifest() -> dict:
    with open(SECRETS_MANIFEST) as f:
        return json.load(f)


def generate_safe_password(length: int = 32) -> str:
    """Generate a password using ADR 0403 safe alphabet."""
    return "".join(secrets.choice(SAFE_ALPHABET) for _ in range(length))


def generate_hex(length: int = 32) -> str:
    return secrets.token_hex(length)


def generate_base64(length: int = 24) -> str:
    return base64.urlsafe_b64encode(secrets.token_bytes(length)).decode()


def generate_ssh_ed25519(path: Path) -> str:
    """Generate a new Ed25519 SSH key pair."""
    if path.exists():
        path.unlink()
    pub_path = path.with_suffix(path.suffix + ".pub")
    if pub_path.exists():
        pub_path.unlink()
    subprocess.run(
        ["ssh-keygen", "-t", "ed25519", "-N", "", "-f", str(path), "-C", "emergency-rotation-2026-04-11"],
        check=True,
        capture_output=True,
    )
    return f"(SSH key pair at {path})"


def generate_rsa_2048(path: Path) -> str:
    """Generate a new RSA 2048-bit private key."""
    subprocess.run(
        ["openssl", "genrsa", "-out", str(path), "2048"],
        check=True,
        capture_output=True,
    )
    return f"(RSA key at {path})"


def classify_tier(secret_id: str, origin: str = "generated_by_repo") -> str:
    """Determine which tier a secret belongs to."""
    if origin in ("provided_externally", "provided_or_generated_externally"):
        return "ext"
    if secret_id in TIER_DEFINITIONS["t1"]["secret_ids"]:
        return "t1"
    for prefix in TIER_DEFINITIONS["t2"]["secret_id_prefixes"]:
        if secret_id.startswith(prefix):
            return "t2"
    return "t3"


def get_generator_for_secret(secret_id: str) -> str:
    """Determine the appropriate value generator for a secret."""
    if secret_id in SPECIAL_HANDLERS:
        return SPECIAL_HANDLERS[secret_id]

    # Heuristic based on secret name patterns
    if "_key" in secret_id and "api" not in secret_id:
        return "hex_32"
    if "secret_key" in secret_id or "encryption" in secret_id:
        return "hex_32"
    if "salt" in secret_id:
        return "hex_16"
    if "token" in secret_id:
        return "hex_32"
    return "text"  # default safe password


def rotate_secret(secret_id: str, secret_def: dict, apply: bool) -> dict:
    """Rotate a single secret. Returns a receipt entry."""
    handler = get_generator_for_secret(secret_id)
    path_str = secret_def.get("path")
    kind = secret_def.get("kind", "file")
    origin = secret_def.get("origin", "generated_by_repo")
    receipt = {
        "id": secret_id,
        "kind": kind,
        "path": path_str,
        "handler": handler,
        "tier": classify_tier(secret_id, origin),
        "status": "planned",
    }

    if handler == "skip":
        receipt["status"] = "skipped"
        receipt["reason"] = "Requires manual rotation or is regenerated by convergence role"
        return receipt

    if secret_id in ENV_NOT_SECRETS:
        receipt["status"] = "skipped"
        receipt["reason"] = "Not a secret (hostname, command template, or identifier)"
        return receipt

    if kind == "env":
        # Self-hosted env-var secrets: persist to ~/.config/codex-secrets/ and .local/
        local_path = ENV_SECRET_LOCAL_PATHS.get(secret_id)
        if local_path:
            if not apply:
                receipt["status"] = "planned"
                receipt["new_value_preview"] = f"(will write to {local_path})"
                return receipt
            new_value = generate_safe_password(32)
            local_path.parent.mkdir(parents=True, exist_ok=True)
            local_path.write_text(new_value + "\n")
            local_path.chmod(0o600)
            receipt["status"] = "rotated"
            receipt["method"] = f"safe_alphabet_32 → {local_path}"
            receipt["path"] = str(local_path)
            return receipt
        receipt["status"] = "skipped"
        receipt["reason"] = "Environment variable without local persistence path"
        return receipt

    if not path_str:
        receipt["status"] = "skipped"
        receipt["reason"] = "No path defined"
        return receipt

    full_path = REPO_ROOT / path_str
    if not apply:
        receipt["status"] = "planned"
        receipt["new_value_preview"] = f"({handler}, will generate on --apply)"
        return receipt

    # Ensure parent directory exists
    full_path.parent.mkdir(parents=True, exist_ok=True)

    if handler == "ssh_ed25519":
        result = generate_ssh_ed25519(full_path)
        receipt["status"] = "rotated"
        receipt["method"] = "ssh-keygen ed25519"
    elif handler == "rsa_2048":
        result = generate_rsa_2048(full_path)
        receipt["status"] = "rotated"
        receipt["method"] = "openssl genrsa 2048"
    elif handler == "json_password":
        # For JSON auth files, update the password field
        try:
            with open(full_path) as f:
                data = json.load(f)
        except (FileNotFoundError, json.JSONDecodeError):
            data = {}
        new_pw = generate_safe_password(32)
        data["password"] = new_pw
        with open(full_path, "w") as f:
            json.dump(data, f, indent=2)
        full_path.chmod(0o600)
        receipt["status"] = "rotated"
        receipt["method"] = "json_password (password field replaced)"
    elif handler == "hex_32":
        new_value = generate_hex(32)
        full_path.write_text(new_value + "\n")
        full_path.chmod(0o600)
        receipt["status"] = "rotated"
        receipt["method"] = "hex_32"
    elif handler == "hex_16":
        new_value = generate_hex(16)
        full_path.write_text(new_value + "\n")
        full_path.chmod(0o600)
        receipt["status"] = "rotated"
        receipt["method"] = "hex_16"
    elif handler == "base64":
        new_value = generate_base64(24)
        full_path.write_text(new_value + "\n")
        full_path.chmod(0o600)
        receipt["status"] = "rotated"
        receipt["method"] = "base64_24"
    else:  # "text" — safe password
        new_value = generate_safe_password(32)
        full_path.write_text(new_value + "\n")
        full_path.chmod(0o600)
        receipt["status"] = "rotated"
        receipt["method"] = "safe_alphabet_32"

    return receipt


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Emergency credential rotation — ADR 0405",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--list", action="store_true", help="List all secrets grouped by tier")
    parser.add_argument("--tier", choices=["t1", "t2", "t3", "ext", "all"], help="Rotation tier to process")
    parser.add_argument("--secret", help="Rotate a single secret by ID")
    parser.add_argument("--plan", action="store_true", help="Show what would be rotated (dry run)")
    parser.add_argument("--apply", action="store_true", help="Actually rotate credentials")
    args = parser.parse_args()

    manifest = load_manifest()
    all_secrets = manifest["secrets"]

    # Include both generated_by_repo AND provided_externally (self-hosted services)
    rotatable = {
        sid: sdef
        for sid, sdef in all_secrets.items()
        if sdef.get("origin") in ("generated_by_repo", "provided_externally", "provided_or_generated_externally")
    }

    if args.list:
        for tier_id in ["t1", "t2", "t3", "ext"]:
            tier_secrets = {
                sid: s
                for sid, s in rotatable.items()
                if classify_tier(sid, s.get("origin", "generated_by_repo")) == tier_id
            }
            tier_label = TIER_DEFINITIONS[tier_id].get("label", tier_id)
            print(f"\n=== {tier_label} ({len(tier_secrets)} secrets) ===")
            for sid in sorted(tier_secrets):
                handler = get_generator_for_secret(sid)
                s = tier_secrets[sid]
                path = s.get("path", s.get("name", "(env)"))
                is_not_secret = sid in ENV_NOT_SECRETS
                is_skip = handler == "skip"
                if is_not_secret:
                    status = "N/A"
                elif is_skip:
                    status = "SKIP"
                elif s.get("kind") == "env" and sid not in ENV_SECRET_LOCAL_PATHS:
                    status = "SKIP"
                else:
                    status = "rotate"
                print(f"  [{status:6s}] {sid:55s} {path}")
        total = len(rotatable)
        will_rotate = sum(
            1
            for sid, s in rotatable.items()
            if get_generator_for_secret(sid) != "skip"
            and sid not in ENV_NOT_SECRETS
            and not (s.get("kind") == "env" and sid not in ENV_SECRET_LOCAL_PATHS)
        )
        print(f"\nTotal: {total} secrets, {will_rotate} will rotate, {total - will_rotate} skipped")
        return

    if not args.tier and not args.secret:
        parser.error("Specify --tier or --secret")

    if args.secret:
        if args.secret not in rotatable:
            print(f"ERROR: '{args.secret}' not found in rotatable secrets", file=sys.stderr)
            sys.exit(1)
        targets = {args.secret: rotatable[args.secret]}
    elif args.tier == "all":
        targets = rotatable
    else:
        targets = {
            sid: s
            for sid, s in rotatable.items()
            if classify_tier(sid, s.get("origin", "generated_by_repo")) == args.tier
        }

    apply = args.apply
    mode = "APPLY" if apply else "PLAN"
    print(f"\n{'=' * 60}")
    print(f"Emergency Credential Rotation — ADR 0405")
    print(f"Mode: {mode}")
    print(f"Scope: {len(targets)} secrets")
    print(f"Timestamp: {dt.datetime.now(dt.timezone.utc).isoformat()}")
    print(f"{'=' * 60}\n")

    receipts = []
    counts = {"rotated": 0, "skipped": 0, "planned": 0, "error": 0}

    for sid in sorted(targets):
        sdef = targets[sid]
        try:
            receipt = rotate_secret(sid, sdef, apply=apply)
        except Exception as exc:
            receipt = {
                "id": sid,
                "status": "error",
                "error": str(exc),
                "tier": classify_tier(sid),
            }
        receipts.append(receipt)
        counts[receipt["status"]] = counts.get(receipt["status"], 0) + 1
        status_icon = {
            "rotated": "+",
            "skipped": "-",
            "planned": "~",
            "error": "!",
        }.get(receipt["status"], "?")
        print(f"  [{status_icon}] {sid:55s} {receipt['status']:8s} {receipt.get('method', receipt.get('reason', ''))}")

    print(f"\n{'=' * 60}")
    print(
        f"Results: {counts.get('rotated', 0)} rotated, {counts.get('skipped', 0)} skipped, "
        f"{counts.get('planned', 0)} planned, {counts.get('error', 0)} errors"
    )
    print(f"{'=' * 60}")

    # Write receipt
    if apply:
        RECEIPT_DIR.mkdir(parents=True, exist_ok=True)
        ts = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        tier_label = args.tier or args.secret or "single"
        receipt_path = RECEIPT_DIR / f"{ts}-emergency-rotation-{tier_label}.json"
        receipt_data = {
            "event": "emergency_credential_rotation",
            "adr": "0405",
            "trigger": "public-release-exposure-2026-04-11",
            "timestamp": dt.datetime.now(dt.timezone.utc).isoformat(),
            "mode": mode,
            "tier": args.tier or "single",
            "summary": counts,
            "entries": receipts,
        }
        with open(receipt_path, "w") as f:
            json.dump(receipt_data, f, indent=2)
        print(f"\nReceipt written to: {receipt_path}")

    # Print convergence instructions
    if apply:
        rotated_services = set()
        for r in receipts:
            if r["status"] == "rotated":
                sid = r["id"]
                # Extract service name from secret ID
                parts = sid.split("_")
                if len(parts) >= 2:
                    service = parts[0]
                    if service in (
                        "keycloak",
                        "openbao",
                        "semaphore",
                        "gitea",
                        "dify",
                        "harbor",
                        "windmill",
                        "grafana",
                        "mattermost",
                        "n8n",
                        "coolify",
                        "plane",
                    ):
                        rotated_services.add(service)
                    elif parts[0] in ("mail", "step", "label", "matrix", "nats", "uptime"):
                        rotated_services.add("_".join(parts[:2]))

        if rotated_services:
            print("\n=== CONVERGENCE REQUIRED ===")
            print("Run these to propagate new credentials to live services:")
            print()
            # Database passwords need Postgres reconvergence first
            print("# Step 1: Reconverge PostgreSQL (propagates new DB passwords)")
            print("make converge-postgres-vm env=production")
            print()
            print("# Step 2: Reconverge Keycloak (propagates new OIDC secrets)")
            print("make converge-keycloak env=production")
            print()
            print("# Step 3: Reconverge each affected service")
            for svc in sorted(rotated_services - {"keycloak", "step", "openbao"}):
                print(f"make converge-{svc.replace('_', '-')} env=production")
            print()
            print("# Step 4: Reconverge OpenBao (re-seeds rotated secrets)")
            print("make converge-openbao env=production")


if __name__ == "__main__":
    main()
