#!/usr/bin/env python3

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent

if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

existing_platform = sys.modules.get("platform")
if existing_platform is not None and not hasattr(existing_platform, "__path__"):
    del sys.modules["platform"]

from platform.repo import TOPOLOGY_HOST_VARS_PATH

from controller_automation_toolkit import emit_cli_error, load_yaml, repo_path

from validation_toolkit import require_int, require_list


STACK_PATH = repo_path("versions", "stack.yaml")
IDENTITY_VARS_PATH = repo_path("inventory", "group_vars", "all", "identity.yml")
LOCAL_IDENTITY_VARS_PATH = repo_path(".local", "identity.yml")
PLATFORM_VARS_PATH = repo_path("inventory", "group_vars", "platform.yml")
SERVICE_CATALOG_PATH = repo_path("config", "service-capability-catalog.json")
CROSS_CUTTING_DNS_DECLARATIONS_PATH = repo_path("config", "generated", "dns-declarations.yaml")
CROSS_CUTTING_NGINX_UPSTREAMS_PATH = repo_path("config", "generated", "nginx-upstreams.yaml")
CROSS_CUTTING_SSO_CLIENTS_PATH = repo_path("config", "generated", "sso-clients.yaml")
CROSS_CUTTING_HAIRPIN_PATH = repo_path("inventory", "group_vars", "platform_hairpin.yml")
CROSS_CUTTING_TLS_CERTS_PATH = repo_path("inventory", "group_vars", "platform_tls_certs.yml")
GENERATED_HEADER = (
    "# Generated by scripts/generate_platform_vars.py from versions/stack.yaml,\n"
    "# inventory/host_vars/proxmox-host.yml,\n"
    "# inventory/group_vars/all/identity.yml, and (when present) .local/identity.yml.\n"
    "# Do not edit by hand — run: make generate-platform-vars\n"
)


def resolve_local_identity_override_path() -> Path | None:
    if LOCAL_IDENTITY_VARS_PATH.is_file():
        return LOCAL_IDENTITY_VARS_PATH
    repo_root = repo_path()
    if ".worktrees" in repo_root.parts:
        main_root = Path(*repo_root.parts[: repo_root.parts.index(".worktrees")])
        candidate = main_root / ".local" / "identity.yml"
        if candidate.is_file():
            return candidate
    return None


PORT_KEYS = (
    "alertmanager_port",
    "monitoring_grafana_port",
    "monitoring_influxdb_port",
    "monitoring_loki_port",
    "monitoring_blackbox_exporter_port",
    "monitoring_prometheus_port",
    "monitoring_tempo_http_port",
    "monitoring_otlp_grpc_port",
    "monitoring_otlp_http_port",
    "mailpit_http_port",
    "mailpit_smtp_port",
    "mail_platform_gateway_port",
    "livekit_signal_port",
    "livekit_tcp_port",
    "livekit_udp_port",
    "ntfy_port",
    "openfga_http_port",
    "openfga_host_proxy_port",
    "openbao_http_port",
    "openbao_proxy_port",
    "redpanda_kafka_port",
    "redpanda_admin_port",
    "redpanda_http_proxy_port",
    "redpanda_schema_registry_port",
    "semaphore_server_port",
    "semaphore_host_proxy_port",
    "windmill_server_port",
    "windmill_host_proxy_port",
    "nomad_server_port",
    "nomad_rpc_port",
    "nomad_serf_port",
    "nomad_host_proxy_port",
    "mattermost_server_port",
    "mattermost_host_proxy_port",
    "matrix_synapse_port",
    "matrix_synapse_host_proxy_port",
    "gitea_http_port",
    "gitea_host_proxy_port",
    "netbox_server_port",
    "netbox_host_proxy_port",
    "gotenberg_port",
    "typesense_port",
    "typesense_host_proxy_port",
    "searxng_port",
    "searxng_host_proxy_port",
    "langfuse_port",
    "plausible_port",
    "minio_api_port",
    "minio_console_port",
    "glitchtip_port",
    "flagsmith_port",
    "lago_api_port",
    "lago_front_port",
    "dify_port",
    "changedetection_port",
    "crawl4ai_port",
    "falco_event_bridge_port",
    "browser_runner_port",
    "grist_port",
    "outline_port",
    "directus_port",
    "label_studio_port",
    "superset_port",
    "piper_port",
    "paperless_port",
    "dozzle_http_port",
    "dozzle_agent_port",
    "excalidraw_port",
    "excalidraw_room_port",
    "woodpecker_http_port",
    "woodpecker_host_proxy_port",
    "ollama_api_port",
    "n8n_port",
    "nextcloud_port",
    "coolify_dashboard_port",
    "coolify_proxy_port",
    "coolify_proxy_tls_port",
    "coolify_host_proxy_port",
    "serverclaw_port",
    "api_gateway_internal_port",
    "platform_context_internal_port",
    "platform_context_host_proxy_port",
    "homepage_port",
    "ops_portal_port",
    "harbor_port",
    "plane_port",
    "plane_host_proxy_port",
    "ntopng_http_port",
    "ntopng_proxy_port",
    "portainer_https_port",
    "portainer_host_proxy_port",
    "step_ca_api_port",
    "step_ca_proxy_port",
    "tika_port",
    "tesseract_ocr_port",
    "headscale_http_port",
    "vaultwarden_https_port",
    "keycloak_internal_http_port",
    "mail_platform_internal_submission_port",
)

MANAGEMENT_IPV4_TOKEN = "{{ management_ipv4 }}"
MANAGEMENT_TAILSCALE_IPV4_TOKEN = "{{ management_tailscale_ipv4 }}"
SESSION_AUTHORITY_SHARED_LOGOUT_PATH = "/.well-known/lv3/session/logout"
SESSION_AUTHORITY_SHARED_PROXY_CLEANUP_PATH = "/.well-known/lv3/session/proxy-logout"
SESSION_AUTHORITY_SHARED_LOGGED_OUT_PATH = "/.well-known/lv3/session/logged-out"
HOST_VAR_TEMPLATE_RE = re.compile(r"{{\s*([a-z0-9_]+(?:\.[a-z0-9_]+)*)\s*}}")
HOST_SELF_TEMPLATE_RE = re.compile(
    r"""{{\s*hostvars\[(?:'|")proxmox-host(?:'|")\]\.([a-z0-9_]+(?:\.[a-z0-9_]+)*)\s*}}"""
)
PORT_ASSIGNMENT_TEMPLATE_RE = re.compile(
    r"""{{\s*(?:hostvars\[(?:'|")proxmox-host(?:'|")\]\.)?platform_port_assignments\.([a-z0-9_]+)\s*}}"""
)
GUEST_IPV4_TEMPLATE_RE = re.compile(
    r"""{{\s*\(proxmox_guests\s+\|\s+selectattr\('name',\s+'equalto',\s+'([^']+)'\)\s+\|\s+map\(attribute='ipv4'\)\s+\|\s+first\)\s*}}"""
)


def yaml_dump(payload: Any) -> str:
    try:
        import yaml
    except ModuleNotFoundError as exc:  # pragma: no cover - direct runtime guard
        raise RuntimeError("Missing dependency: PyYAML. Run via 'uvx --from pyyaml python ...'.") from exc

    class IndentedSafeDumper(yaml.SafeDumper):
        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow, False)

    return yaml.dump(payload, Dumper=IndentedSafeDumper, sort_keys=False)


def require_mapping(value: Any, path: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{path} must be a mapping")
    return value


def require_string(value: Any, path: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{path} must be a non-empty string")
    return value


def require_string_list(value: Any, path: str) -> list[str]:
    return [require_string(item, f"{path}[{index}]") for index, item in enumerate(require_list(value, path))]


def load_service_classification_map() -> dict[str, dict[str, Any]]:
    payload = json.loads(SERVICE_CATALOG_PATH.read_text(encoding="utf-8"))
    services = require_list(payload.get("services"), "config/service-capability-catalog.json.services")
    by_id: dict[str, dict[str, Any]] = {}
    for index, entry in enumerate(services):
        entry = require_mapping(entry, f"config/service-capability-catalog.json.services[{index}]")
        service_id = require_string(entry.get("id"), f"config/service-capability-catalog.json.services[{index}].id")
        by_id[service_id] = entry
    return by_id


def resolve_dns_target(target: str, host_vars: dict[str, Any]) -> str:
    if target == MANAGEMENT_IPV4_TOKEN:
        return require_string(host_vars.get("management_ipv4"), "host_vars.management_ipv4")
    if target == MANAGEMENT_TAILSCALE_IPV4_TOKEN:
        return require_string(host_vars.get("management_tailscale_ipv4"), "host_vars.management_tailscale_ipv4")
    resolved = resolve_host_var_template(target, host_vars, "dns target")
    if resolved is target:
        return target
    return require_string(resolved, "dns target")


def resolve_host_var_template(value: Any, host_vars: dict[str, Any], path: str) -> Any:
    if not isinstance(value, str):
        return value
    match = HOST_VAR_TEMPLATE_RE.fullmatch(value)
    if match is None:
        return value
    return lookup_host_var_path(host_vars, match.group(1), path)


def lookup_host_var_path(host_vars: dict[str, Any], dotted_path: str, path: str) -> Any:
    keys = dotted_path.split(".")
    current: Any = host_vars
    traversed = []
    for key in keys:
        traversed.append(key)
        if not isinstance(current, dict) or key not in current:
            raise ValueError(f"{path} references unknown host var {'.'.join(traversed)!r}")
        current = current[key]
    return current


def render_known_templates_in_string(
    value: str,
    host_vars: dict[str, Any],
    guest_ipv4_by_name: dict[str, str],
    ports: dict[str, int],
    path: str,
) -> str:
    def replace_host_self(match: re.Match[str]) -> str:
        resolved = lookup_host_var_path(host_vars, match.group(1), path)
        return str(resolved)

    def replace_port_assignment(match: re.Match[str]) -> str:
        port_key = match.group(1)
        if port_key not in ports:
            raise ValueError(f"{path} references unknown port assignment {port_key!r}")
        return str(ports[port_key])

    def replace_guest_ipv4(match: re.Match[str]) -> str:
        guest_name = match.group(1)
        if guest_name not in guest_ipv4_by_name:
            raise ValueError(f"{path} references unknown proxmox guest {guest_name!r}")
        return guest_ipv4_by_name[guest_name]

    def replace_host_var(match: re.Match[str]) -> str:
        resolved = lookup_host_var_path(host_vars, match.group(1), path)
        return str(resolved)

    rendered = value
    previous = None
    while rendered != previous:
        previous = rendered
        rendered = PORT_ASSIGNMENT_TEMPLATE_RE.sub(replace_port_assignment, rendered)
        rendered = HOST_SELF_TEMPLATE_RE.sub(replace_host_self, rendered)
        rendered = GUEST_IPV4_TEMPLATE_RE.sub(replace_guest_ipv4, rendered)
        rendered = HOST_VAR_TEMPLATE_RE.sub(replace_host_var, rendered)
    return rendered


def render_known_templates(
    value: Any,
    host_vars: dict[str, Any],
    guest_ipv4_by_name: dict[str, str],
    ports: dict[str, int],
    path: str,
) -> Any:
    if isinstance(value, dict):
        return {
            key: render_known_templates(
                item,
                host_vars,
                guest_ipv4_by_name,
                ports,
                f"{path}.{key}",
            )
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [
            render_known_templates(item, host_vars, guest_ipv4_by_name, ports, f"{path}[{index}]")
            for index, item in enumerate(value)
        ]
    if isinstance(value, str):
        return render_known_templates_in_string(value, host_vars, guest_ipv4_by_name, ports, path)
    return value


def extract_port(raw_url: str, path: str) -> int:
    match = re.search(r":(\d+)(?:/[^}]*)?$", raw_url)
    if match is None:
        raise ValueError(f"{path} must end with a port number")
    return int(match.group(1))


def service_url(scheme: str, host: str, port: int, suffix: str = "") -> str:
    return f"{scheme}://{host}:{port}{suffix}"


def load_sources() -> tuple[dict[str, Any], dict[str, Any]]:
    stack = require_mapping(load_yaml(STACK_PATH), str(STACK_PATH))
    host_vars = require_mapping(load_yaml(TOPOLOGY_HOST_VARS_PATH), str(TOPOLOGY_HOST_VARS_PATH))
    # Merge identity vars (platform_domain, operator email/name, etc.) into host_vars
    # so HOST_VAR_TEMPLATE_RE can resolve {{ platform_domain }} in strings like
    # "nginx.{{ platform_domain }}". Identity vars are loaded second so host_vars
    # wins on any key collision (operator-specific values take precedence).
    identity_vars = require_mapping(load_yaml(IDENTITY_VARS_PATH), str(IDENTITY_VARS_PATH))
    # Only merge plain string/int/bool values — skip Jinja2-templated values that
    # reference other identity vars (e.g. keycloak_oidc_issuer_url) to avoid
    # partially-rendered strings propagating into platform.yml.
    for key, val in identity_vars.items():
        if key not in host_vars and isinstance(val, (str, int, bool)) and "{{" not in str(val):
            host_vars[key] = val
    # Apply the local identity overlay (ADR 0407) — real deployment values override
    # the generic committed placeholders (e.g. example.com, 203.0.113.1).
    #
    # CRITICAL: This mirrors what _resolve_identity_override() does for Ansible runs
    # (injecting -e @.local/identity.yml as highest-precedence extra-vars).  Without
    # this step the generator would bake fake/sanitised IPs and domains into the
    # derived structures inside platform.yml (platform_host.management.ipv4, DNS
    # targets, monitoring scrape targets, …) that Ansible extra-vars cannot override
    # because they are nested mappings, not flat variables.
    #
    # Result: the private repo's platform.yml contains real deployment values; the
    # publish pipeline (make publish-serverclaw) sanitises them for the public mirror.
    local_identity_path = resolve_local_identity_override_path()
    if local_identity_path is not None:
        local_identity = require_mapping(load_yaml(local_identity_path), str(local_identity_path))
        for key, val in local_identity.items():
            # Local overlay WINS — override any committed placeholder with real value.
            # Skip Jinja2 templates (e.g. derived URLs that reference other vars).
            if isinstance(val, (str, int, bool)) and "{{" not in str(val):
                host_vars[key] = val
    return stack, host_vars


def load_optional_cross_cutting_generated_inputs() -> dict[str, Any]:
    """Load ADR 0374 generated artifacts when present.

    These files are intentionally ignored because they contain deployment-specific
    values. They still need to flow into platform.yml so playbooks that only load
    platform.yml can consume the generated hairpin/TLS/registry context.
    """

    def optional_yaml(path: Path) -> Any:
        if not path.exists():
            return None
        return load_yaml(path)

    def optional_mapping(path: Path, key: str) -> dict[str, Any]:
        payload = optional_yaml(path)
        if payload is None:
            return {}
        payload = require_mapping(payload, str(path))
        value = payload.get(key, {})
        return require_mapping(value, f"{path}.{key}") if value else {}

    def optional_list(path: Path, key: str) -> list[Any]:
        payload = optional_yaml(path)
        if payload is None:
            return []
        payload = require_mapping(payload, str(path))
        value = payload.get(key, [])
        return require_list(value, f"{path}.{key}") if value else []

    return {
        "dns_declarations": optional_mapping(CROSS_CUTTING_DNS_DECLARATIONS_PATH, "dns_records"),
        "nginx_upstreams": optional_list(CROSS_CUTTING_NGINX_UPSTREAMS_PATH, "platform_nginx_upstreams"),
        "sso_clients": optional_mapping(CROSS_CUTTING_SSO_CLIENTS_PATH, "sso_clients"),
        "hairpin_hosts": optional_list(CROSS_CUTTING_HAIRPIN_PATH, "platform_hairpin_nat_hosts"),
        "tls_certs": optional_mapping(CROSS_CUTTING_TLS_CERTS_PATH, "platform_tls_certs"),
    }


def build_guest_catalog(host_vars: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any], dict[str, str]]:
    guests = []
    by_name: dict[str, Any] = {}
    by_role: dict[str, Any] = {}
    ipv4_by_name: dict[str, str] = {}
    for index, guest in enumerate(require_list(host_vars.get("proxmox_guests"), "host_vars.proxmox_guests")):
        guest = require_mapping(guest, f"host_vars.proxmox_guests[{index}]")
        guest_copy = copy.deepcopy(guest)
        name = require_string(guest_copy.get("name"), f"host_vars.proxmox_guests[{index}].name")
        role = require_string(guest_copy.get("role"), f"host_vars.proxmox_guests[{index}].role")
        ipv4 = require_string(guest_copy.get("ipv4"), f"host_vars.proxmox_guests[{index}].ipv4")
        guests.append(guest_copy)
        by_name[name] = copy.deepcopy(guest_copy)
        by_role[role] = copy.deepcopy(guest_copy)
        ipv4_by_name[name] = ipv4
    return {"list": guests, "by_name": by_name, "by_role": by_role}, by_name, ipv4_by_name


def build_dns_records(
    service_topology: dict[str, Any],
    host_vars: dict[str, Any],
) -> dict[str, list[dict[str, Any]]]:
    def append_record(visibility: str, record: dict[str, Any]) -> None:
        bucket = records.setdefault(visibility, [])
        if record not in bucket:
            bucket.append(record)

    def managed_zone_name(service: dict[str, Any], path: str) -> str:
        dns = require_mapping(service.get("dns"), f"{path}.dns")
        public_hostname = require_string(service.get("public_hostname"), f"{path}.public_hostname")
        dns_name = require_string(dns.get("name"), f"{path}.dns.name")
        if dns_name == "@":
            return public_hostname
        prefix = f"{dns_name}."
        if not public_hostname.startswith(prefix):
            raise ValueError(
                f"{path}.public_hostname must start with {prefix!r} so wildcard aliases can derive the zone name"
            )
        zone_name = public_hostname[len(prefix) :]
        if not zone_name:
            raise ValueError(f"{path}.public_hostname must include a managed DNS zone suffix")
        return zone_name

    def relative_record_name(fqdn: str, zone_name: str, path: str) -> str:
        if fqdn == zone_name:
            return "@"
        suffix = f".{zone_name}"
        if not fqdn.endswith(suffix):
            raise ValueError(f"{path} must stay inside the managed DNS zone {zone_name}")
        return fqdn[: -len(suffix)]

    records = {
        "public": [
            {
                "name": "@",
                "type": "A",
                "value": require_string(host_vars.get("management_ipv4"), "host_vars.management_ipv4"),
                "ttl": 60,
            }
        ],
        "tailnet": [],
    }
    for service_id, service in service_topology.items():
        dns = service.get("dns")
        if not dns or not dns.get("managed"):
            continue
        visibility = dns["visibility"]
        append_record(
            visibility,
            {
                "name": dns["name"],
                "type": dns["type"],
                "value": dns["target"],
                "ttl": dns["ttl"],
            },
        )
        additional_records = require_list(
            dns.get("additional_records", []),
            f"service_topology.{service_id}.dns.additional_records",
        )
        for index, extra_record in enumerate(additional_records):
            extra_record = require_mapping(
                extra_record,
                f"service_topology.{service_id}.dns.additional_records[{index}]",
            )
            append_record(
                visibility,
                {
                    "name": require_string(
                        extra_record.get("name"),
                        f"service_topology.{service_id}.dns.additional_records[{index}].name",
                    ),
                    "type": require_string(
                        extra_record.get("type"),
                        f"service_topology.{service_id}.dns.additional_records[{index}].type",
                    ),
                    "value": resolve_dns_target(
                        require_string(
                            extra_record.get("target"),
                            f"service_topology.{service_id}.dns.additional_records[{index}].target",
                        ),
                        host_vars,
                    ),
                    "ttl": require_int(
                        extra_record.get("ttl"),
                        f"service_topology.{service_id}.dns.additional_records[{index}].ttl",
                    ),
                },
            )
        edge = require_mapping(service.get("edge", {}), f"service_topology.{service_id}.edge")
        aliases = require_string_list(edge.get("aliases", []), f"service_topology.{service_id}.edge.aliases")
        if visibility != "public" or not aliases:
            continue
        zone_name = managed_zone_name(service, f"service_topology.{service_id}")
        for index, alias in enumerate(aliases):
            append_record(
                visibility,
                {
                    "name": relative_record_name(
                        alias, zone_name, f"service_topology.{service_id}.edge.aliases[{index}]"
                    ),
                    "type": dns["type"],
                    "value": dns["target"],
                    "ttl": dns["ttl"],
                },
            )

    for index, record in enumerate(host_vars.get("mail_platform_dns_records", [])):
        record = require_mapping(record, f"host_vars.mail_platform_dns_records[{index}]")
        append_record(
            "public",
            {
                "name": require_string(record.get("name"), f"host_vars.mail_platform_dns_records[{index}].name"),
                "type": require_string(record.get("type"), f"host_vars.mail_platform_dns_records[{index}].type"),
                "value": resolve_dns_target(
                    require_string(
                        record.get("value"),
                        f"host_vars.mail_platform_dns_records[{index}].value",
                    ),
                    host_vars,
                ),
                "ttl": require_int(record.get("ttl"), f"host_vars.mail_platform_dns_records[{index}].ttl"),
            },
        )
    return records


def build_service_urls(
    service_id: str,
    service: dict[str, Any],
    host_vars: dict[str, Any],
    guest_ipv4_by_name: dict[str, str],
    ports: dict[str, int],
    stack: dict[str, Any],
) -> tuple[dict[str, Any], dict[str, str]]:
    host_id = require_string(stack["desired_state"]["host_id"], "versions/stack.yaml.desired_state.host_id")
    tailscale_ipv4 = require_string(host_vars.get("management_tailscale_ipv4"), "host_vars.management_tailscale_ipv4")
    owning_vm = service["owning_vm"]
    private_ip = tailscale_ipv4 if owning_vm == host_id else guest_ipv4_by_name[owning_vm]
    urls: dict[str, str] = {}
    port_map: dict[str, Any] = {}

    public_hostname = service.get("public_hostname")
    console_public_hostname = service.get("console_public_hostname")
    if public_hostname:
        urls["public"] = f"https://{public_hostname}"

    if service_id == "alertmanager":
        urls["internal"] = service_url("http", private_ip, ports["alertmanager_port"])
        port_map["internal"] = ports["alertmanager_port"]
    elif service_id == "grafana":
        urls["internal"] = service_url("http", private_ip, ports["monitoring_grafana_port"])
        urls["influxdb"] = service_url("http", private_ip, ports["monitoring_influxdb_port"])
        urls["loki_push"] = service_url("http", private_ip, ports["monitoring_loki_port"], "/loki/api/v1/push")
        urls["prometheus"] = service_url("http", private_ip, ports["monitoring_prometheus_port"])
        urls["tempo"] = service_url("http", private_ip, ports["monitoring_tempo_http_port"])
        urls["otlp_grpc"] = service_url("http", private_ip, ports["monitoring_otlp_grpc_port"])
        urls["otlp_http"] = service_url("http", private_ip, ports["monitoring_otlp_http_port"], "/v1/traces")
        port_map["internal"] = ports["monitoring_grafana_port"]
    elif service_id == "uptime_kuma":
        urls["internal"] = service_url("http", private_ip, extract_port(service["edge"]["upstream"], "edge.upstream"))
        port_map["internal"] = extract_port(service["edge"]["upstream"], "edge.upstream")
    elif service_id == "keycloak":
        urls["internal"] = service_url("http", private_ip, ports["keycloak_internal_http_port"])
        port_map["internal"] = ports["keycloak_internal_http_port"]
    elif service_id == "mail_platform":
        urls["private_api"] = require_string(
            stack["desired_state"]["mail"]["api_private_url"],
            "versions/stack.yaml.desired_state.mail.api_private_url",
        )
        port_map["private_api"] = ports["mail_platform_gateway_port"]
    elif service_id == "step_ca":
        urls["internal"] = service_url("https", private_ip, ports["step_ca_api_port"])
        urls["controller"] = service_url("https", tailscale_ipv4, ports["step_ca_proxy_port"])
        port_map["internal"] = ports["step_ca_api_port"]
        port_map["controller"] = ports["step_ca_proxy_port"]
    elif service_id == "tika":
        urls["internal"] = service_url("http", private_ip, ports["tika_port"])
        port_map["internal"] = ports["tika_port"]
    elif service_id == "tesseract_ocr":
        urls["internal"] = service_url("http", private_ip, ports["tesseract_ocr_port"])
        port_map["internal"] = ports["tesseract_ocr_port"]
    elif service_id == "livekit":
        urls["internal"] = service_url("http", private_ip, ports["livekit_signal_port"])
        port_map["internal"] = ports["livekit_signal_port"]
        port_map["media_tcp"] = ports["livekit_tcp_port"]
        port_map["media_udp"] = ports["livekit_udp_port"]
    elif service_id == "semaphore":
        urls["internal"] = service_url("http", private_ip, ports["semaphore_server_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["semaphore_host_proxy_port"])
        port_map["internal"] = ports["semaphore_server_port"]
        port_map["controller"] = ports["semaphore_host_proxy_port"]
    elif service_id == "windmill":
        urls["internal"] = service_url("http", private_ip, ports["windmill_server_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["windmill_host_proxy_port"])
        port_map["internal"] = ports["windmill_server_port"]
        port_map["controller"] = ports["windmill_host_proxy_port"]
    elif service_id == "nomad":
        urls["internal"] = service_url("https", private_ip, ports["nomad_server_port"])
        urls["controller"] = service_url("https", tailscale_ipv4, ports["nomad_host_proxy_port"])
        port_map["internal"] = ports["nomad_server_port"]
        port_map["controller"] = ports["nomad_host_proxy_port"]
    elif service_id == "mattermost":
        urls["internal"] = service_url("http", private_ip, ports["mattermost_server_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["mattermost_host_proxy_port"])
        port_map["internal"] = ports["mattermost_server_port"]
        port_map["controller"] = ports["mattermost_host_proxy_port"]
    elif service_id == "matrix_synapse":
        urls["internal"] = service_url("http", private_ip, ports["matrix_synapse_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["matrix_synapse_host_proxy_port"])
        port_map["internal"] = ports["matrix_synapse_port"]
        port_map["controller"] = ports["matrix_synapse_host_proxy_port"]
    elif service_id == "gitea":
        urls["internal"] = service_url("http", private_ip, ports["gitea_http_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["gitea_host_proxy_port"])
        port_map["internal"] = ports["gitea_http_port"]
        port_map["controller"] = ports["gitea_host_proxy_port"]
    elif service_id == "keycloak":
        urls["internal"] = service_url("http", private_ip, ports["keycloak_internal_http_port"])
        port_map["internal"] = ports["keycloak_internal_http_port"]
    elif service_id == "netbox":
        urls["internal"] = service_url("http", private_ip, ports["netbox_server_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["netbox_host_proxy_port"])
        port_map["internal"] = ports["netbox_server_port"]
        port_map["controller"] = ports["netbox_host_proxy_port"]
    elif service_id == "gotenberg":
        urls["internal"] = service_url("http", private_ip, ports["gotenberg_port"])
        port_map["internal"] = ports["gotenberg_port"]
    elif service_id == "typesense":
        urls["internal"] = service_url("http", private_ip, ports["typesense_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["typesense_host_proxy_port"])
        port_map["internal"] = ports["typesense_port"]
        port_map["controller"] = ports["typesense_host_proxy_port"]
    elif service_id == "searxng":
        public_hostname = service.get("public_hostname")
        urls["internal"] = service_url("http", private_ip, ports["searxng_port"])
        if public_hostname:
            if ports["searxng_host_proxy_port"] == 80:
                urls["public"] = f"http://{public_hostname}"
            else:
                urls["public"] = service_url("http", public_hostname, ports["searxng_host_proxy_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["searxng_host_proxy_port"])
        port_map["internal"] = ports["searxng_port"]
        port_map["controller"] = ports["searxng_host_proxy_port"]
    elif service_id == "langfuse":
        urls["internal"] = service_url("http", private_ip, ports["langfuse_port"])
        port_map["internal"] = ports["langfuse_port"]
    elif service_id == "flagsmith":
        urls["internal"] = service_url("http", private_ip, ports["flagsmith_port"])
        port_map["internal"] = ports["flagsmith_port"]
    elif service_id == "plausible":
        urls["internal"] = service_url("http", private_ip, ports["plausible_port"])
        port_map["internal"] = ports["plausible_port"]
    elif service_id == "minio":
        urls["internal"] = service_url("http", private_ip, ports["minio_api_port"])
        urls["console_internal"] = service_url("http", private_ip, ports["minio_console_port"])
        if console_public_hostname:
            urls["console_public"] = f"https://{console_public_hostname}"
        port_map["internal"] = ports["minio_api_port"]
        port_map["console"] = ports["minio_console_port"]
    elif service_id == "lago":
        urls["internal"] = service_url("http", private_ip, ports["lago_front_port"])
        urls["api"] = service_url("http", private_ip, ports["lago_api_port"])
        port_map["internal"] = ports["lago_front_port"]
        port_map["api"] = ports["lago_api_port"]
    elif service_id == "mailpit":
        urls["internal"] = service_url("http", private_ip, ports["mailpit_http_port"])
        urls["smtp"] = service_url("smtp", private_ip, ports["mailpit_smtp_port"])
        port_map["internal"] = ports["mailpit_http_port"]
        port_map["smtp"] = ports["mailpit_smtp_port"]
    elif service_id == "redpanda":
        urls["internal"] = service_url("kafka", private_ip, ports["redpanda_kafka_port"])
        urls["admin"] = service_url("http", private_ip, ports["redpanda_admin_port"])
        urls["http_proxy"] = service_url("http", private_ip, ports["redpanda_http_proxy_port"])
        urls["schema_registry"] = service_url("http", private_ip, ports["redpanda_schema_registry_port"])
        port_map["internal"] = ports["redpanda_kafka_port"]
        port_map["admin"] = ports["redpanda_admin_port"]
        port_map["http_proxy"] = ports["redpanda_http_proxy_port"]
        port_map["schema_registry"] = ports["redpanda_schema_registry_port"]
    elif service_id == "glitchtip" or service_id == "glitchtip":
        urls["internal"] = service_url("http", private_ip, ports["glitchtip_port"])
        port_map["internal"] = ports["glitchtip_port"]
    elif service_id == "dify":
        urls["internal"] = service_url("http", private_ip, ports["dify_port"])
        port_map["internal"] = ports["dify_port"]
    elif service_id == "changedetection":
        urls["internal"] = service_url("http", private_ip, ports["changedetection_port"])
        port_map["internal"] = ports["changedetection_port"]
    elif service_id == "crawl4ai":
        urls["internal"] = service_url("http", private_ip, ports["crawl4ai_port"])
        port_map["internal"] = ports["crawl4ai_port"]
    elif service_id == "browser_runner":
        urls["internal"] = service_url("http", private_ip, ports["browser_runner_port"])
        port_map["internal"] = ports["browser_runner_port"]
    elif service_id == "grist":
        urls["internal"] = service_url("http", private_ip, ports["grist_port"])
        port_map["internal"] = ports["grist_port"]
    elif service_id == "outline":
        urls["internal"] = service_url("http", private_ip, ports["outline_port"])
        port_map["internal"] = ports["outline_port"]
    elif service_id == "directus":
        urls["internal"] = service_url("http", private_ip, ports["directus_port"])
        port_map["internal"] = ports["directus_port"]
    elif service_id == "label_studio":
        urls["internal"] = service_url("http", private_ip, ports["label_studio_port"])
        port_map["internal"] = ports["label_studio_port"]
    elif service_id == "superset":
        urls["internal"] = service_url("http", private_ip, ports["superset_port"])
        port_map["internal"] = ports["superset_port"]
    elif service_id == "paperless":
        urls["internal"] = service_url("http", private_ip, ports["paperless_port"])
        port_map["internal"] = ports["paperless_port"]
    elif service_id == "harbor":
        urls["internal"] = service_url("http", private_ip, ports["harbor_port"])
        port_map["internal"] = ports["harbor_port"]
    elif service_id == "plane":
        urls["internal"] = service_url("http", private_ip, ports["plane_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["plane_host_proxy_port"])
        port_map["internal"] = ports["plane_port"]
        port_map["controller"] = ports["plane_host_proxy_port"]
    elif service_id == "woodpecker":
        urls["internal"] = service_url("http", private_ip, ports["woodpecker_http_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["woodpecker_host_proxy_port"])
        port_map["internal"] = ports["woodpecker_http_port"]
        port_map["controller"] = ports["woodpecker_host_proxy_port"]
    elif service_id == "dozzle":
        urls["internal"] = service_url("http", private_ip, ports["dozzle_http_port"])
        port_map["internal"] = ports["dozzle_http_port"]
    elif service_id == "excalidraw":
        urls["internal"] = service_url("http", private_ip, ports["excalidraw_port"])
        port_map["internal"] = ports["excalidraw_port"]
    elif service_id == "ollama":
        urls["internal"] = service_url("http", private_ip, ports["ollama_api_port"])
        port_map["internal"] = ports["ollama_api_port"]
    elif service_id == "piper":
        urls["internal"] = service_url("http", private_ip, ports["piper_port"])
        port_map["internal"] = ports["piper_port"]
    elif service_id == "n8n":
        urls["internal"] = service_url("http", private_ip, ports["n8n_port"])
        port_map["internal"] = ports["n8n_port"]
    elif service_id == "nextcloud":
        urls["internal"] = service_url("http", private_ip, ports["nextcloud_port"])
        port_map["internal"] = ports["nextcloud_port"]
    elif service_id == "coolify":
        urls["internal"] = service_url("http", private_ip, ports["coolify_dashboard_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["coolify_host_proxy_port"])
        port_map["internal"] = ports["coolify_dashboard_port"]
        port_map["controller"] = ports["coolify_host_proxy_port"]
    elif service_id == "coolify_apps":
        urls["internal"] = service_url("https", private_ip, ports["coolify_proxy_tls_port"])
        port_map["internal"] = ports["coolify_proxy_tls_port"]
    elif service_id == "serverclaw":
        urls["internal"] = service_url("http", private_ip, ports["serverclaw_port"])
        port_map["internal"] = ports["serverclaw_port"]
    elif service_id == "api_gateway":
        urls["internal"] = service_url("http", private_ip, ports["api_gateway_internal_port"])
        port_map["internal"] = ports["api_gateway_internal_port"]
    elif service_id == "headscale":
        urls["internal"] = service_url(
            "http",
            require_string(host_vars.get("proxmox_internal_ipv4"), "host_vars.proxmox_internal_ipv4"),
            ports["headscale_http_port"],
        )
        port_map["internal"] = ports["headscale_http_port"]
    elif service_id == "openbao":
        urls["internal"] = service_url("https", private_ip, ports["openbao_proxy_port"])
        urls["controller"] = service_url("https", tailscale_ipv4, ports["openbao_proxy_port"])
        port_map["internal"] = ports["openbao_proxy_port"]
        port_map["controller"] = ports["openbao_proxy_port"]
    elif service_id == "openfga":
        urls["internal"] = service_url("http", private_ip, ports["openfga_http_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["openfga_host_proxy_port"])
        port_map["internal"] = ports["openfga_http_port"]
        port_map["controller"] = ports["openfga_host_proxy_port"]
    elif service_id == "platform_context_api":
        urls["internal"] = service_url("http", private_ip, ports["platform_context_internal_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["platform_context_host_proxy_port"])
        port_map["internal"] = ports["platform_context_internal_port"]
        port_map["controller"] = ports["platform_context_host_proxy_port"]
    elif service_id == "ntfy":
        urls["internal"] = service_url("http", private_ip, ports["ntfy_port"])
        port_map["internal"] = ports["ntfy_port"]
    elif service_id == "ops_portal":
        urls["internal"] = service_url("http", private_ip, ports["ops_portal_port"])
        port_map["internal"] = ports["ops_portal_port"]
    elif service_id == "homepage":
        urls["internal"] = service_url("http", private_ip, ports["homepage_port"])
        port_map["internal"] = ports["homepage_port"]
    elif service_id == "status_page":
        urls["internal"] = service_url("http", private_ip, 3001)
        port_map["internal"] = 3001
    elif service_id == "ntopng":
        urls["internal"] = service_url("http", "127.0.0.1", ports["ntopng_http_port"])
        urls["controller"] = service_url("http", tailscale_ipv4, ports["ntopng_proxy_port"])
        port_map["internal"] = ports["ntopng_http_port"]
        port_map["controller"] = ports["ntopng_proxy_port"]
    elif service_id == "portainer":
        urls["internal"] = service_url("https", private_ip, ports["portainer_https_port"])
        urls["controller"] = service_url("https", tailscale_ipv4, ports["portainer_host_proxy_port"])
        port_map["internal"] = ports["portainer_https_port"]
        port_map["controller"] = ports["portainer_host_proxy_port"]
    elif service_id == "vaultwarden":
        urls["internal"] = service_url("https", private_ip, ports["vaultwarden_https_port"])
        if public_hostname:
            urls["controller"] = f"https://{public_hostname}"
        else:
            urls["controller"] = service_url("https", tailscale_ipv4, 443)
        port_map["internal"] = ports["vaultwarden_https_port"]
        port_map["controller"] = 443
    elif service_id == "postgres":
        urls["internal"] = service_url("postgresql", service.get("public_hostname", private_ip), 5432)
        urls["controller"] = service_url("postgresql", tailscale_ipv4, 5432)
        port_map["internal"] = 5432
        port_map["controller"] = 5432
    elif service_id == "proxmox_ui":
        urls["controller"] = service_url("https", tailscale_ipv4, 8006, "/")
        port_map["controller"] = 8006

    return port_map, urls


def build_service_topology(
    stack: dict[str, Any],
    host_vars: dict[str, Any],
    guest_ipv4_by_name: dict[str, str],
    ports: dict[str, int],
    service_classification_by_id: dict[str, dict[str, Any]],
) -> dict[str, Any]:
    raw_topology = require_mapping(host_vars.get("lv3_service_topology"), "host_vars.lv3_service_topology")
    host_id = require_string(stack["desired_state"]["host_id"], "versions/stack.yaml.desired_state.host_id")
    tailscale_ipv4 = require_string(host_vars.get("management_tailscale_ipv4"), "host_vars.management_tailscale_ipv4")

    resolved: dict[str, Any] = {}
    for service_id, raw_service in raw_topology.items():
        raw_service = require_mapping(raw_service, f"host_vars.lv3_service_topology.{service_id}")
        service = copy.deepcopy(raw_service)
        owning_vm = require_string(service.get("owning_vm"), f"host_vars.lv3_service_topology.{service_id}.owning_vm")
        if "private_ip" in service:
            private_ip_candidate = require_string(
                service.get("private_ip"),
                f"host_vars.lv3_service_topology.{service_id}.private_ip",
            )
            private_ip_candidate = require_string(
                resolve_host_var_template(
                    private_ip_candidate,
                    host_vars,
                    f"host_vars.lv3_service_topology.{service_id}.private_ip",
                ),
                f"host_vars.lv3_service_topology.{service_id}.private_ip",
            )
            if "proxmox_guests" in private_ip_candidate:
                private_ip = tailscale_ipv4 if owning_vm == host_id else guest_ipv4_by_name[owning_vm]
            else:
                private_ip = private_ip_candidate
        else:
            private_ip = tailscale_ipv4 if owning_vm == host_id else guest_ipv4_by_name[owning_vm]
        service["service_id"] = service_id
        service["private_ip"] = private_ip

        service_catalog_entry = service_classification_by_id.get(service_id, {})
        for field in (
            "runtime_pool",
            "deployment_surface",
            "restart_domain",
            "api_contract_ref",
            "mobility_tier",
        ):
            if field in service_catalog_entry:
                service[field] = copy.deepcopy(service_catalog_entry[field])

        if "dns" in service:
            service["dns"]["target"] = resolve_dns_target(
                require_string(service["dns"]["target"], f"host_vars.lv3_service_topology.{service_id}.dns.target"),
                host_vars,
            )

        ports_map, urls = build_service_urls(
            service_id,
            service,
            host_vars,
            guest_ipv4_by_name,
            ports,
            stack,
        )
        service["ports"] = ports_map
        service["urls"] = urls

        if "edge" in service and service["edge"].get("kind") == "proxy" and "upstream" not in service["edge"]:
            service["edge"]["upstream"] = urls["internal"]
        if "edge" in service and "action_url" in service["edge"] and service_id == "proxmox_ui":
            service["edge"]["action_url"] = urls["controller"]
        if "access" in service and "controller" in urls:
            service["access"]["url"] = urls["controller"]
        service = render_known_templates(
            service,
            host_vars,
            guest_ipv4_by_name,
            ports,
            f"host_vars.lv3_service_topology.{service_id}",
        )

        resolved[service_id] = service
    return resolved


def resolve_tcp_proxy_port(value: Any, ports: dict[str, int]) -> int:
    if isinstance(value, int):
        return value
    value = require_string(value, "proxy port template")
    match = re.fullmatch(r"{{\s*(?:platform_port_assignments\.)?([a-z0-9_]+)\s*}}", value)
    if match is None:
        raise ValueError(f"unsupported proxy port template: {value}")
    key = match.group(1)
    if key not in ports:
        raise ValueError(f"unknown proxy port key in template: {key}")
    return ports[key]


def build_tcp_proxies(host_vars: dict[str, Any], ports: dict[str, int]) -> list[dict[str, Any]]:
    resolved = []
    for index, proxy in enumerate(
        require_list(host_vars.get("proxmox_tailscale_tcp_proxies"), "host_vars.proxmox_tailscale_tcp_proxies")
    ):
        proxy = require_mapping(proxy, f"host_vars.proxmox_tailscale_tcp_proxies[{index}]")
        resolved.append(
            {
                "name": require_string(proxy.get("name"), f"host_vars.proxmox_tailscale_tcp_proxies[{index}].name"),
                "listen_address": require_string(
                    resolve_host_var_template(
                        proxy.get("listen_address"),
                        host_vars,
                        f"host_vars.proxmox_tailscale_tcp_proxies[{index}].listen_address",
                    ),
                    f"host_vars.proxmox_tailscale_tcp_proxies[{index}].listen_address",
                ),
                "listen_port": resolve_tcp_proxy_port(proxy.get("listen_port"), ports),
                "upstream_host": require_string(
                    proxy.get("upstream_host"),
                    f"host_vars.proxmox_tailscale_tcp_proxies[{index}].upstream_host",
                ),
                "upstream_port": resolve_tcp_proxy_port(proxy.get("upstream_port"), ports),
            }
        )
    return resolved


def build_platform_session_authority(service_topology: dict[str, Any], host_vars: dict[str, Any]) -> dict[str, str]:
    keycloak_service = require_mapping(
        service_topology.get("keycloak"),
        "platform_service_topology.keycloak",
    )
    ops_portal_service = require_mapping(
        service_topology.get("ops_portal"),
        "platform_service_topology.ops_portal",
    )
    keycloak_public_url = require_string(
        require_mapping(keycloak_service.get("urls"), "platform_service_topology.keycloak.urls").get("public"),
        "platform_service_topology.keycloak.urls.public",
    )
    ops_portal_public_url = require_string(
        require_mapping(
            ops_portal_service.get("urls"),
            "platform_service_topology.ops_portal.urls",
        ).get("public"),
        "platform_service_topology.ops_portal.urls.public",
    )
    return {
        "authority_hostname": require_string(
            ops_portal_service.get("public_hostname"),
            "platform_service_topology.ops_portal.public_hostname",
        ),
        "ops_portal_client_id": "ops-portal-oauth",
        "keycloak_logout_url": f"{keycloak_public_url}/realms/lv3/protocol/openid-connect/logout",
        "oauth2_proxy_sign_out_url": f"{ops_portal_public_url}/oauth2/sign_out",
        "shared_logout_path": SESSION_AUTHORITY_SHARED_LOGOUT_PATH,
        "shared_logout_url": f"{ops_portal_public_url}{SESSION_AUTHORITY_SHARED_LOGOUT_PATH}",
        "shared_proxy_cleanup_path": SESSION_AUTHORITY_SHARED_PROXY_CLEANUP_PATH,
        "shared_proxy_cleanup_url": f"{ops_portal_public_url}{SESSION_AUTHORITY_SHARED_PROXY_CLEANUP_PATH}",
        "shared_logged_out_path": SESSION_AUTHORITY_SHARED_LOGGED_OUT_PATH,
        "shared_logged_out_url": f"{ops_portal_public_url}{SESSION_AUTHORITY_SHARED_LOGGED_OUT_PATH}",
        # oauth2-proxy session cookie name and domain — mirrors public_edge_oidc_auth defaults
        "cookie_name": "_lv3_ops_portal_proxy",
        "cookie_domain": f".{host_vars['platform_domain']}",
    }


def _assert_no_host_proxy_port_collisions(resolved_ports: dict[str, int]) -> None:
    """Fail if any two _host_proxy_port keys share the same port number.

    All host-proxy ports bind on the same controller host interface, so a
    collision causes a silent service outage rather than a startup error.
    """
    proxy_ports: dict[int, str] = {}
    collisions: list[str] = []
    for key, value in resolved_ports.items():
        if not key.endswith("_host_proxy_port"):
            continue
        if value in proxy_ports:
            collisions.append(f"  port {value}: {proxy_ports[value]!r} and {key!r}")
        else:
            proxy_ports[value] = key
    if collisions:
        raise ValueError(
            "Duplicate _host_proxy_port values found in platform_port_assignments "
            "(all host-proxy ports share one controller interface):\n" + "\n".join(collisions)
        )


def build_platform_vars(
    stack: dict[str, Any] | None = None,
    host_vars: dict[str, Any] | None = None,
) -> dict[str, Any]:
    if stack is None or host_vars is None:
        stack, host_vars = load_sources()

    ports = require_mapping(host_vars.get("platform_port_assignments"), "host_vars.platform_port_assignments")
    resolved_ports = {
        key: require_int(ports.get(key), f"host_vars.platform_port_assignments.{key}") for key in PORT_KEYS
    }
    _assert_no_host_proxy_port_collisions(resolved_ports)
    guest_catalog, guest_by_name, guest_ipv4_by_name = build_guest_catalog(host_vars)
    service_classification_by_id = load_service_classification_map()
    service_topology = build_service_topology(
        stack,
        host_vars,
        guest_ipv4_by_name,
        resolved_ports,
        service_classification_by_id,
    )
    session_authority = build_platform_session_authority(service_topology, host_vars)
    dns_records = build_dns_records(service_topology, host_vars)
    tcp_proxies = build_tcp_proxies(host_vars, resolved_ports)
    cross_cutting_inputs = load_optional_cross_cutting_generated_inputs()
    monitoring_service = service_topology["grafana"]
    mail_service = service_topology["mail_platform"]
    mattermost_service = service_topology["mattermost"]
    matrix_synapse_service = service_topology["matrix_synapse"]
    gitea_service = service_topology["gitea"]
    minio_service = service_topology["minio"]
    netbox_service = service_topology["netbox"]
    plane_service = service_topology["plane"]
    woodpecker_service = service_topology["woodpecker"]
    api_gateway_service = service_topology["api_gateway"]
    headscale_service = service_topology["headscale"]
    openbao_service = service_topology["openbao"]
    openfga_service = service_topology["openfga"]
    platform_context_service = service_topology["platform_context_api"]
    portainer_service = service_topology["portainer"]
    vaultwarden_service = service_topology["vaultwarden"]
    postgres_service = service_topology["postgres"]
    step_ca_service = service_topology["step_ca"]
    typesense_service = service_topology["typesense"]
    semaphore_service = service_topology["semaphore"]
    uptime_kuma_service = service_topology["uptime_kuma"]
    windmill_service = service_topology["windmill"]
    nomad_service = service_topology["nomad"]
    host_id = require_string(stack["desired_state"]["host_id"], "versions/stack.yaml.desired_state.host_id")
    postgres_ha = require_mapping(host_vars.get("postgres_ha"), "host_vars.postgres_ha")
    postgres_primary_inventory_host = require_string(
        postgres_ha.get("initial_primary"), "host_vars.postgres_ha.initial_primary"
    )
    postgres_primary_ip = require_string(
        guest_by_name.get(postgres_primary_inventory_host, {}).get("ipv4"),
        f"host_vars.proxmox_guests[{postgres_primary_inventory_host}].ipv4",
    )

    platform_vars = {
        "platform_generation": {
            "stack_source": str(STACK_PATH.relative_to(repo_path())),
            "host_vars_source": str(TOPOLOGY_HOST_VARS_PATH.relative_to(repo_path())),
        },
        "platform_host": {
            "id": host_id,
            "public_hostname": require_string(host_vars.get("host_public_hostname"), "host_vars.host_public_hostname"),
            "management": {
                "interface": require_string(host_vars.get("management_interface"), "host_vars.management_interface"),
                "ipv4": require_string(host_vars.get("management_ipv4"), "host_vars.management_ipv4"),
                "ipv4_cidr": require_int(host_vars.get("management_ipv4_cidr"), "host_vars.management_ipv4_cidr"),
                "gateway4": require_string(host_vars.get("management_gateway4"), "host_vars.management_gateway4"),
                "ipv6": require_string(host_vars.get("management_ipv6"), "host_vars.management_ipv6"),
                "ipv6_cidr": require_int(host_vars.get("management_ipv6_cidr"), "host_vars.management_ipv6_cidr"),
                "gateway6": require_string(host_vars.get("management_gateway6"), "host_vars.management_gateway6"),
                "tailscale_ipv4": require_string(
                    host_vars.get("management_tailscale_ipv4"), "host_vars.management_tailscale_ipv4"
                ),
            },
            "network": {
                "wan_bridge": require_string(host_vars.get("proxmox_wan_bridge"), "host_vars.proxmox_wan_bridge"),
                "internal_bridge": require_string(
                    host_vars.get("proxmox_internal_bridge"), "host_vars.proxmox_internal_bridge"
                ),
                "internal_ipv4": require_string(
                    host_vars.get("proxmox_internal_ipv4"), "host_vars.proxmox_internal_ipv4"
                ),
                "internal_cidr": require_int(host_vars.get("proxmox_internal_cidr"), "host_vars.proxmox_internal_cidr"),
                "internal_network": require_string(
                    host_vars.get("proxmox_internal_network"), "host_vars.proxmox_internal_network"
                ),
                "public_edge_ipv4": require_string(
                    host_vars.get("proxmox_public_edge_ipv4"), "host_vars.proxmox_public_edge_ipv4"
                ),
                "public_ingress_tcp_ports": require_list(
                    host_vars.get("proxmox_public_ingress_tcp_ports"),
                    "host_vars.proxmox_public_ingress_tcp_ports",
                ),
                "public_ingress_tcp_forwards": copy.deepcopy(
                    require_list(
                        host_vars.get("proxmox_public_ingress_tcp_forwards"),
                        "host_vars.proxmox_public_ingress_tcp_forwards",
                    )
                ),
                "tailscale_hostname": require_string(
                    host_vars.get("proxmox_tailscale_hostname"), "host_vars.proxmox_tailscale_hostname"
                ),
                "tailscale_advertise_routes": copy.deepcopy(
                    [
                        resolve_host_var_template(
                            item,
                            host_vars,
                            "host_vars.proxmox_tailscale_advertise_routes",
                        )
                        for item in require_list(
                            host_vars.get("proxmox_tailscale_advertise_routes"),
                            "host_vars.proxmox_tailscale_advertise_routes",
                        )
                    ]
                ),
                "tailscale_operator_target_guest": require_string(
                    host_vars.get("proxmox_tailscale_operator_target_guest"),
                    "host_vars.proxmox_tailscale_operator_target_guest",
                ),
                "tailscale_tcp_proxies": tcp_proxies,
            },
        },
        "platform_ports": resolved_ports,
        "platform_port_assignments": copy.deepcopy(resolved_ports),
        "platform_guest_catalog": guest_catalog,
        "platform_service_topology": service_topology,
        "platform_session_authority": session_authority,
        "platform_dns_records": dns_records,
        "platform_dns_declarations": cross_cutting_inputs["dns_declarations"],
        "platform_nginx_upstreams": cross_cutting_inputs["nginx_upstreams"],
        "platform_sso_clients": cross_cutting_inputs["sso_clients"],
        "platform_hairpin_nat_hosts": cross_cutting_inputs["hairpin_hosts"],
        "platform_tls_certs": cross_cutting_inputs["tls_certs"],
        "platform_management_allowed_tcp_ports": [
            resolved_ports["ntopng_proxy_port"],
            resolved_ports["gitea_host_proxy_port"],
            resolved_ports["netbox_host_proxy_port"],
            resolved_ports["typesense_host_proxy_port"],
            resolved_ports["step_ca_proxy_port"],
            resolved_ports["openbao_proxy_port"],
            resolved_ports["openfga_host_proxy_port"],
            resolved_ports["semaphore_host_proxy_port"],
            resolved_ports["headscale_http_port"],
            resolved_ports["windmill_host_proxy_port"],
            resolved_ports["nomad_host_proxy_port"],
            resolved_ports["plane_host_proxy_port"],
            resolved_ports["woodpecker_host_proxy_port"],
            resolved_ports["mattermost_host_proxy_port"],
            resolved_ports["matrix_synapse_host_proxy_port"],
            resolved_ports["platform_context_host_proxy_port"],
            resolved_ports["portainer_host_proxy_port"],
            443,
        ],
        "public_edge_service_topology": copy.deepcopy(service_topology),
        "uptime_kuma_service_topology": copy.deepcopy(uptime_kuma_service),
        "hetzner_dns_records": dns_records["public"],
        "platform_postgres_host": postgres_service["public_hostname"],
        "openbao_postgres_host": postgres_primary_ip,
        "openbao_http_extra_bind_addresses": render_known_templates(
            copy.deepcopy(
                require_list(
                    host_vars.get("openbao_http_extra_bind_addresses", []),
                    "host_vars.openbao_http_extra_bind_addresses",
                )
            ),
            host_vars,
            guest_ipv4_by_name,
            resolved_ports,
            "host_vars.openbao_http_extra_bind_addresses",
        ),
        "openbao_controller_url": openbao_service["urls"]["controller"],
        "openfga_http_port": resolved_ports["openfga_http_port"],
        "openfga_host_proxy_port": resolved_ports["openfga_host_proxy_port"],
        "openfga_controller_url": openfga_service["urls"]["controller"],
        "semaphore_server_port": resolved_ports["semaphore_server_port"],
        "semaphore_host_proxy_port": resolved_ports["semaphore_host_proxy_port"],
        "semaphore_private_base_url": semaphore_service["urls"]["internal"],
        "semaphore_controller_url": semaphore_service["urls"]["controller"],
        "netbox_host_proxy_port": resolved_ports["netbox_host_proxy_port"],
        "netbox_controller_url": netbox_service["urls"]["controller"],
        "typesense_port": resolved_ports["typesense_port"],
        "typesense_host_proxy_port": resolved_ports["typesense_host_proxy_port"],
        "typesense_controller_url": typesense_service["urls"]["controller"],
        "plane_port": resolved_ports["plane_port"],
        "plane_host_proxy_port": resolved_ports["plane_host_proxy_port"],
        "plane_private_base_url": plane_service["urls"]["internal"],
        "plane_controller_url": plane_service["urls"]["controller"],
        "woodpecker_http_port": resolved_ports["woodpecker_http_port"],
        "woodpecker_host_proxy_port": resolved_ports["woodpecker_host_proxy_port"],
        "woodpecker_private_base_url": woodpecker_service["urls"]["internal"],
        "woodpecker_controller_url": woodpecker_service["urls"]["controller"],
        "api_gateway_internal_port": resolved_ports["api_gateway_internal_port"],
        "api_gateway_public_url": api_gateway_service["urls"]["public"],
        "api_gateway_internal_url": api_gateway_service["urls"]["internal"],
        "headscale_http_port": resolved_ports["headscale_http_port"],
        "headscale_public_url": headscale_service["urls"]["public"],
        "headscale_internal_url": headscale_service["urls"]["internal"],
        "ntopng_proxy_port": resolved_ports["ntopng_proxy_port"],
        "ntopng_operator_url": service_topology["ntopng"]["urls"]["controller"],
        "mattermost_server_port": resolved_ports["mattermost_server_port"],
        "mattermost_host_proxy_port": resolved_ports["mattermost_host_proxy_port"],
        "mattermost_private_base_url": mattermost_service["urls"]["internal"],
        "mattermost_controller_url": mattermost_service["urls"]["controller"],
        "matrix_synapse_port": resolved_ports["matrix_synapse_port"],
        "matrix_synapse_host_proxy_port": resolved_ports["matrix_synapse_host_proxy_port"],
        "matrix_synapse_private_base_url": matrix_synapse_service["urls"]["internal"],
        "matrix_synapse_controller_url": matrix_synapse_service["urls"]["controller"],
        "matrix_synapse_public_url": matrix_synapse_service["urls"]["public"],
        "gitea_http_port": resolved_ports["gitea_http_port"],
        "gitea_host_proxy_port": resolved_ports["gitea_host_proxy_port"],
        "gitea_root_url": gitea_service["urls"].get("public", gitea_service["urls"]["controller"]),
        "gitea_private_base_url": gitea_service["urls"]["internal"],
        "gitea_controller_url": gitea_service["urls"]["controller"],
        "minio_public_url": minio_service["urls"]["public"],
        "minio_console_public_url": minio_service["urls"]["console_public"],
        "platform_context_internal_port": resolved_ports["platform_context_internal_port"],
        "platform_context_host_proxy_port": resolved_ports["platform_context_host_proxy_port"],
        "platform_context_private_url": f"http://127.0.0.1:{resolved_ports['platform_context_internal_port']}",
        "platform_context_controller_url": platform_context_service["urls"]["controller"],
        "portainer_host_proxy_port": resolved_ports["portainer_host_proxy_port"],
        "portainer_controller_url": portainer_service["urls"]["controller"],
        "vaultwarden_https_port": resolved_ports["vaultwarden_https_port"],
        "vaultwarden_controller_url": vaultwarden_service["urls"]["controller"],
        "step_ca_api_port": resolved_ports["step_ca_api_port"],
        "step_ca_proxy_port": resolved_ports["step_ca_proxy_port"],
        "step_ca_internal_url": step_ca_service["urls"]["internal"],
        "step_ca_controller_url": step_ca_service["urls"]["controller"],
        "windmill_host_proxy_port": resolved_ports["windmill_host_proxy_port"],
        "windmill_controller_url": windmill_service["urls"]["controller"],
        "nomad_host_proxy_port": resolved_ports["nomad_host_proxy_port"],
        "nomad_controller_url": nomad_service["urls"]["controller"],
        "monitoring_loki_push_api_url": monitoring_service["urls"]["loki_push"],
        "proxmox_management_allowed_tcp_ports": [
            resolved_ports["ntopng_proxy_port"],
            resolved_ports["gitea_host_proxy_port"],
            resolved_ports["netbox_host_proxy_port"],
            resolved_ports["typesense_host_proxy_port"],
            resolved_ports["step_ca_proxy_port"],
            resolved_ports["openbao_proxy_port"],
            resolved_ports["openfga_host_proxy_port"],
            resolved_ports["semaphore_host_proxy_port"],
            resolved_ports["headscale_http_port"],
            resolved_ports["windmill_host_proxy_port"],
            resolved_ports["nomad_host_proxy_port"],
            resolved_ports["plane_host_proxy_port"],
            resolved_ports["woodpecker_host_proxy_port"],
            resolved_ports["mattermost_host_proxy_port"],
            resolved_ports["matrix_synapse_host_proxy_port"],
            resolved_ports["platform_context_host_proxy_port"],
            resolved_ports["portainer_host_proxy_port"],
            443,
        ],
        "mail_platform_private_api_url": mail_service["urls"]["private_api"],
    }
    platform_vars.update(resolved_ports)
    return platform_vars


def render_platform_vars(payload: dict[str, Any]) -> str:
    return GENERATED_HEADER + yaml_dump(payload)


def write_platform_vars(output_path: Path = PLATFORM_VARS_PATH) -> int:
    rendered = render_platform_vars(build_platform_vars())
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered)
    print(f"Wrote generated platform vars to {output_path}")
    return 0


def check_platform_vars(output_path: Path = PLATFORM_VARS_PATH) -> int:
    rendered = render_platform_vars(build_platform_vars())
    current = output_path.read_text() if output_path.exists() else ""
    if rendered != current:
        print(
            "Generated platform vars are stale. Run "
            "'uvx --from pyyaml python scripts/generate_platform_vars.py --write' "
            "or 'make generate-platform-vars'.",
            file=sys.stderr,
        )
        return 2
    print("Generated platform vars OK")
    return 0


def dry_run(output_path: Path = PLATFORM_VARS_PATH) -> int:
    del output_path
    sys.stdout.write(render_platform_vars(build_platform_vars()))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the committed platform facts library from canonical stack and host vars."
    )
    parser.add_argument("--write", action="store_true", help="Write inventory/group_vars/platform.yml.")
    parser.add_argument("--check", action="store_true", help="Exit non-zero if platform.yml is stale.")
    parser.add_argument("--dry-run", action="store_true", help="Print the generated YAML and exit.")
    args = parser.parse_args()

    selected = [args.write, args.check, args.dry_run]
    if sum(1 for enabled in selected if enabled) != 1:
        parser.print_help()
        return 0

    try:
        if args.write:
            return write_platform_vars()
        if args.check:
            return check_platform_vars()
        return dry_run()
    except (OSError, RuntimeError, ValueError) as exc:
        return emit_cli_error("Platform vars generator", exc)


if __name__ == "__main__":
    sys.exit(main())
