#!/usr/bin/env python3
"""Generate a draft release-PR body — ADR 0473 phase 11.3.

Inspects:
  - VERSION
  - changelog.md (the `## Unreleased` section)
  - docs/release-notes/<version>.md (if present)
  - receipts/health-probes/ (most recent files)

Writes a Markdown PR body with the five sections agents draft by hand
on every release: Summary, Release checklist, Test plan, ADR ref,
Postmortem ref.

The output is a draft — agents redact + extend it. Baseline saves
the LLM round-trips spent re-deriving the same sections from the same
state.

Usage:
  python scripts/generate_pr_body.py            # write to stdout
  python scripts/generate_pr_body.py --write    # write to build/pr-body-draft.md

Exit:
  0  rendered (stdout or `--write`)
  2  invocation error
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
VERSION_PATH = REPO_ROOT / "VERSION"
CHANGELOG_PATH = REPO_ROOT / "changelog.md"
RELEASE_NOTES_DIR = REPO_ROOT / "docs" / "release-notes"
HEALTH_PROBES_DIR = REPO_ROOT / "receipts" / "health-probes"
DEFAULT_OUTPUT = REPO_ROOT / "build" / "pr-body-draft.md"


def read_version(path: Path = VERSION_PATH) -> str:
    if not path.is_file():
        return "(unknown)"
    return path.read_text(encoding="utf-8").strip()


def extract_unreleased(changelog_path: Path = CHANGELOG_PATH) -> list[str]:
    """Return the bullets under '## Unreleased' (up to the next H2)."""
    if not changelog_path.is_file():
        return []
    text = changelog_path.read_text(encoding="utf-8")
    match = re.search(r"^## Unreleased\s*$(.*?)^## ", text, flags=re.S | re.M)
    if not match:
        return []
    section = match.group(1).strip()
    bullets: list[str] = []
    current: list[str] = []
    for line in section.splitlines():
        if line.startswith("- "):
            if current:
                bullets.append(" ".join(current).strip())
            current = [line.lstrip("- ").rstrip()]
        elif line.startswith("  ") and current:
            current.append(line.strip())
        elif line.strip() == "":
            if current:
                bullets.append(" ".join(current).strip())
                current = []
        else:
            if current:
                current.append(line.strip())
    if current:
        bullets.append(" ".join(current).strip())
    return [b for b in bullets if b]


def detect_release_artifacts(version: str) -> dict[str, bool]:
    return {
        "VERSION": VERSION_PATH.is_file(),
        f"docs/release-notes/{version}.md": (RELEASE_NOTES_DIR / f"{version}.md").is_file(),
        "build/platform-manifest.json": (REPO_ROOT / "build" / "platform-manifest.json").is_file(),
        "build/onboarding/": (REPO_ROOT / "build" / "onboarding").is_dir(),
        "docs/adr/.index.yaml": (REPO_ROOT / "docs" / "adr" / ".index.yaml").is_file(),
    }


def recent_health_probes(limit: int = 5, probes_dir: Path = HEALTH_PROBES_DIR) -> list[str]:
    if not probes_dir.is_dir():
        return []
    files = sorted(probes_dir.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True)
    return [str(p.as_posix()) for p in files[:limit] if p.is_file()]


def find_adr_refs(bullets: list[str]) -> list[str]:
    pattern = re.compile(r"ADR\s+(\d{4})", re.I)
    found: list[str] = []
    for bullet in bullets:
        for match in pattern.finditer(bullet):
            ref = f"ADR {match.group(1)}"
            if ref not in found:
                found.append(ref)
    return found


def render(*, version: str, bullets: list[str], artifacts: dict[str, bool], probes: list[str], adrs: list[str]) -> str:
    lines: list[str] = []
    lines.append("## Summary")
    lines.append("")
    if bullets:
        for bullet in bullets:
            lines.append(f"- {bullet}")
    else:
        lines.append("- (no Unreleased entries found)")
    lines.append("")

    lines.append("## Release checklist")
    lines.append("")
    for label, present in artifacts.items():
        mark = "x" if present else " "
        lines.append(f"- [{mark}] {label}")
    lines.append("")

    lines.append("## Test plan")
    lines.append("")
    if probes:
        lines.append("Recent health-probe receipts:")
        for path in probes:
            lines.append(f"- {path}")
    else:
        lines.append("- (no health-probe receipts found — run scripts/run_health_probes.py)")
    lines.append("")

    if adrs:
        lines.append("## ADR refs")
        lines.append("")
        for adr in adrs:
            lines.append(f"- {adr}")
        lines.append("")

    lines.append(f"_Draft generated by `scripts/generate_pr_body.py` for version {version}._")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("--write", action="store_true", help="Write to build/pr-body-draft.md instead of stdout.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Override --write target.")
    args = parser.parse_args(argv)

    # Read module-level paths each time so monkeypatched test fixtures take effect.
    version = read_version(VERSION_PATH)
    bullets = extract_unreleased(CHANGELOG_PATH)
    artifacts = detect_release_artifacts(version)
    probes = recent_health_probes(probes_dir=HEALTH_PROBES_DIR)
    adrs = find_adr_refs(bullets)
    body = render(version=version, bullets=bullets, artifacts=artifacts, probes=probes, adrs=adrs)

    if args.write:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(body, encoding="utf-8")
        print(f"generate_pr_body: wrote {out_path.as_posix()}", file=sys.stderr)
    else:
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
