#!/usr/bin/env python3
"""Synthesise one-line docstrings for validators missing one — ADR 0451 phase 6.3.

`build/validator-catalogue.yaml` flags 14/30 validators with
`purpose: (no docstring)`. Hand-writing 14 docstrings is the obvious
fix; this script automates the boring 80%: synthesise a one-line
docstring from the validator's filename and inject it as the first
line of the file.

Synthesised docstrings carry a `# TODO: refine — auto-generated by
heal_validator_docstrings.py` marker so reviewers know to upgrade
them. The catalogue regenerator (`generate_validator_catalogue.py`)
picks the new docstrings up automatically on the next run.

Title synthesis rule:

  1. Strip the leading `validate_` or `check_` prefix.
  2. Strip the file extension.
  3. Replace underscores with spaces.
  4. Capitalise the first word; leave others lowercase unless
     they're known acronyms (DNS, TLS, SSO, NATS, ADR, JSON, YAML).
  5. Wrap the title verb form: "Validate <noun phrase>." or
     "Check <noun phrase>." based on the prefix.

Modes:

  --dry-run (default)   List the docstrings that WOULD be written.
  --apply               Write the docstrings to disk.
  --json                Emit the proposed-changes payload as JSON.

The script does NOT touch a file whose existing docstring is non-empty
— even if `validator-catalogue.yaml` says it's empty (cache drift is
possible). Re-running after `--apply` should leave the file unchanged.

Exit:

    0   any mode completed successfully
    1   --apply failed mid-write (partial state surfaced in stderr)
    2   invocation error
"""

from __future__ import annotations

import argparse
import ast
import json
import sys
from dataclasses import dataclass, asdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = REPO_ROOT / "scripts"
CATALOGUE_PATH = REPO_ROOT / "build" / "validator-catalogue.yaml"

# Common acronyms the title-casing pass should preserve in upper case.
_ACRONYMS = frozenset(
    {
        "ADR",
        "API",
        "CI",
        "CLI",
        "DNS",
        "JSON",
        "NATS",
        "SLO",
        "SSO",
        "TLS",
        "URL",
        "YAML",
    }
)

_TODO_MARKER = "# TODO: refine — auto-generated by heal_validator_docstrings.py"


@dataclass(frozen=True)
class Proposal:
    path: str  # repo-relative
    title: str  # synthesised docstring text
    inserted: bool  # True if --apply wrote it; False in dry-run

    def to_dict(self) -> dict:
        return asdict(self)


def synthesise_title(filename: str) -> str:
    """Return a one-sentence docstring derived from the filename.

    Examples:

      validate_dns_declarations.py → "Validate DNS declarations."
      check_role_argument_specs.sh → "Check role argument specs."
    """
    stem = filename
    if stem.endswith(".py"):
        stem = stem[:-3]
    elif stem.endswith(".sh"):
        stem = stem[:-3]
    if stem.startswith("validate_"):
        verb = "Validate"
        rest = stem[len("validate_") :]
    elif stem.startswith("check_"):
        verb = "Check"
        rest = stem[len("check_") :]
    else:
        verb = "Run"
        rest = stem
    words = rest.split("_")
    rendered: list[str] = []
    for i, w in enumerate(words):
        if not w:
            continue
        upper = w.upper()
        if upper in _ACRONYMS:
            rendered.append(upper)
        elif i == 0:
            rendered.append(w.lower())
        else:
            rendered.append(w.lower())
    if not rendered:
        return f"{verb}."
    title = " ".join(rendered)
    return f"{verb} {title}."


def already_has_docstring(path: Path) -> bool:
    """Return True if the script has a non-empty top-level docstring.

    Defensive — `--apply` consults this even when catalogue flags the
    file as missing one, because the catalogue may be stale relative to
    the on-disk state.
    """
    if path.suffix == ".py":
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except (OSError, SyntaxError):
            return False
        return bool(ast.get_docstring(tree))
    if path.suffix == ".sh":
        text = path.read_text(encoding="utf-8", errors="replace")
        # Treat a contiguous comment block of >1 substantive line after
        # the shebang as "has docstring". Single-shebang or single-line
        # commented files are still candidates.
        non_shebang_comments = [line.lstrip("# ").rstrip() for line in text.splitlines()[1:6] if line.startswith("#")]
        non_empty = [c for c in non_shebang_comments if c.strip()]
        return len(non_empty) >= 2
    return False


def render_python_docstring(title: str) -> str:
    """Return a 4-line block: blank, triple-quoted docstring, blank.

    Format:

        \"\"\"<title>

        # TODO: refine — auto-generated by ...
        \"\"\"

    The TODO line lives INSIDE the docstring so it's discoverable via
    grep but doesn't clutter import-time `__doc__` for tools that read
    only the first line.
    """
    return f'"""{title}\n\n{_TODO_MARKER}\n"""\n'


def render_shell_docstring(title: str) -> str:
    """Return a comment block to insert after the shebang."""
    return f"# {title}\n# {_TODO_MARKER}\n"


def insert_into_python(path: Path, title: str) -> None:
    text = path.read_text(encoding="utf-8")
    docstring = render_python_docstring(title)
    if text.startswith("#!"):
        # Insert AFTER the shebang line, preserving trailing newline.
        first_nl = text.find("\n")
        head = text[: first_nl + 1] if first_nl != -1 else text + "\n"
        rest = text[first_nl + 1 :] if first_nl != -1 else ""
        path.write_text(head + docstring + rest, encoding="utf-8")
    else:
        path.write_text(docstring + text, encoding="utf-8")


def insert_into_shell(path: Path, title: str) -> None:
    text = path.read_text(encoding="utf-8")
    block = render_shell_docstring(title)
    if text.startswith("#!"):
        first_nl = text.find("\n")
        head = text[: first_nl + 1] if first_nl != -1 else text + "\n"
        rest = text[first_nl + 1 :] if first_nl != -1 else ""
        path.write_text(head + block + rest, encoding="utf-8")
    else:
        path.write_text(block + text, encoding="utf-8")


def propose(filename: str, *, scripts_dir: Path) -> Proposal | None:
    """Return a Proposal for `filename`, or None if it already has a
    docstring (no work to do)."""
    path = scripts_dir / filename
    if not path.is_file():
        return None
    if already_has_docstring(path):
        return None
    title = synthesise_title(filename)
    # Express the path relative to REPO_ROOT when it lives under it
    # (production), else keep an absolute path (tmp_path-based tests).
    try:
        rel = str(path.relative_to(REPO_ROOT))
    except ValueError:
        rel = str(path)
    return Proposal(path=rel, title=title, inserted=False)


def run(filenames: list[str], *, scripts_dir: Path, apply: bool) -> list[Proposal]:
    out: list[Proposal] = []
    for name in filenames:
        proposal = propose(name, scripts_dir=scripts_dir)
        if proposal is None:
            continue
        if apply:
            path = scripts_dir / name
            if path.suffix == ".py":
                insert_into_python(path, proposal.title)
            elif path.suffix == ".sh":
                insert_into_shell(path, proposal.title)
            out.append(Proposal(path=proposal.path, title=proposal.title, inserted=True))
        else:
            out.append(proposal)
    return out


# ---------------------------------------------------------------------------
# Catalogue load — discovers which files need backfilling
# ---------------------------------------------------------------------------


def load_missing_docstring_filenames(catalogue_path: Path) -> list[str]:
    """Return the filenames flagged `purpose: (no docstring)` in the
    catalogue. Returns an empty list when the catalogue is missing or
    malformed (caller surfaces that as exit 0 with "nothing to do")."""
    if not catalogue_path.is_file():
        return []
    try:
        import yaml

        data = yaml.safe_load(catalogue_path.read_text()) or {}
    except Exception:
        return []
    out: list[str] = []
    for v in data.get("validators") or []:
        if not isinstance(v, dict):
            continue
        if v.get("purpose") == "(no docstring)":
            name = v.get("name")
            if isinstance(name, str):
                out.append(name)
    return out


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "--catalogue",
        default=str(CATALOGUE_PATH),
        help="Path to validator-catalogue.yaml (default: build/validator-catalogue.yaml)",
    )
    parser.add_argument(
        "--scripts-dir",
        default=str(SCRIPTS_DIR),
        help="Path to scripts/ directory (default: <repo>/scripts)",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write the synthesised docstrings (default: dry-run).",
    )
    parser.add_argument("--json", action="store_true", help="Emit JSON output.")
    parser.add_argument(
        "--filenames",
        nargs="*",
        help="Override: backfill only these filenames. Default: read from catalogue.",
    )
    args = parser.parse_args(argv)

    if args.filenames:
        names = list(args.filenames)
    else:
        names = load_missing_docstring_filenames(Path(args.catalogue))

    if not names:
        if args.json:
            print(json.dumps({"proposals": []}))
        else:
            print("heal_validator_docstrings: no validators missing docstrings.")
        return 0

    try:
        proposals = run(names, scripts_dir=Path(args.scripts_dir), apply=args.apply)
    except OSError as exc:
        print(f"heal_validator_docstrings: write failed: {exc}", file=sys.stderr)
        return 1

    if args.json:
        print(
            json.dumps(
                {
                    "mode": "apply" if args.apply else "dry_run",
                    "proposals": [p.to_dict() for p in proposals],
                },
                indent=2,
            )
        )
    else:
        verb = "wrote" if args.apply else "would write"
        print(f"heal_validator_docstrings: {verb} {len(proposals)} docstring(s).")
        for p in proposals:
            print(f'  {p.path}: "{p.title}"')
        if not args.apply and proposals:
            print("\nPass --apply to write these docstrings.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
