#!/usr/bin/env python3
"""
Provision Plane Project for ADR Governance

Creates the 'adr-index' Plane project and API token programmatically.
This script is idempotent - can be run multiple times safely.

Usage:
  python scripts/provision_plane_adr_project.py \
    --plane-url http://10.10.10.20:8093/api/v1 \
    --workspace-slug default \
    --output-file .local/plane.env

Environment Variables:
  PLANE_ADMIN_TOKEN: Admin token for Plane (required for project creation)
  PLANE_URL: Plane API URL (override --plane-url)
  PLANE_WORKSPACE_SLUG: Workspace slug (override --workspace-slug)

Exit codes:
  0 = success (project created or already exists)
  1 = error (missing credentials, API failure, etc.)
"""

import os
import sys
import argparse
from pathlib import Path
from typing import Optional

# Add repo root to path for relative imports
sys.path.insert(0, str(Path(__file__).parent.parent))

try:
    from platform.ansible.plane import PlaneSessionClient, PlaneClient
except ImportError as e:
    print(f"ERROR: Could not import PlaneClient: {e}", file=sys.stderr)
    print("Ensure platform/ansible/plane.py exists", file=sys.stderr)
    sys.exit(1)


def provision_adr_project(
    plane_url: str,
    admin_token: str,
    workspace_slug: str,
    output_file: Optional[str] = None,
) -> dict:
    """
    Provision Plane project for ADR governance.

    Returns: dict with 'project_id', 'api_token', 'workspace_slug'
    """
    print(f"[*] Connecting to Plane at {plane_url}")
    print(f"[*] Workspace: {workspace_slug}")

    # Create session client for project/token management
    session_client = PlaneSessionClient(
        base_url=plane_url.rsplit("/api/v1", 1)[0],  # Remove /api/v1 suffix
        verify_ssl=True,
    )

    # Step 1: Create or get project
    print("\n[*] Creating/verifying 'adr-index' project...")
    try:
        project = session_client.ensure_project(
            workspace_slug=workspace_slug,
            name="Architecture Decisions",
            identifier="adr-index",
            description="ADR index: All architecture decision records with implementation status",
        )
        project_id = project["id"]
        print(f"[✓] Project ready: {project['name']} (ID: {project_id})")
    except Exception as e:
        print(f"[✗] Failed to create/get project: {e}", file=sys.stderr)
        raise

    # Step 2: Create API token
    print("\n[*] Creating API token for ADR governance sync...")
    try:
        token_response = session_client.create_api_token(
            payload={
                "label": "adr-governance-sync",
                "description": "Token for syncing ADRs to Plane (pre-commit hook, sync script, audit)",
            }
        )
        api_token = token_response["token"]
        print(f"[✓] API token created: {api_token[:20]}...")
    except Exception as e:
        print(f"[✗] Failed to create API token: {e}", file=sys.stderr)
        raise

    # Step 3: Save credentials to file
    if output_file:
        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        env_content = f"""# Plane API Credentials for ADR Governance
# Generated by: scripts/provision_plane_adr_project.py
# DO NOT COMMIT THIS FILE (it's in .gitignore)

# Plane API Key - Auto-generated for adr-governance-sync
PLANE_API_KEY={api_token}

# Plane API Base URL
PLANE_URL={plane_url}

# Plane Project ID for ADRs
PLANE_PROJECT_ID={project_id}

# Workspace slug
PLANE_WORKSPACE_SLUG={workspace_slug}
"""

        with open(output_path, "w") as f:
            f.write(env_content)

        # Restrict permissions (avoid storing secrets with world-readable perms)
        output_path.chmod(0o600)

        print(f"\n[✓] Credentials saved to {output_file}")
        print("[!] File permissions: 0o600 (owner read-write only)")

    return {
        "project_id": project_id,
        "api_token": api_token,
        "workspace_slug": workspace_slug,
        "plane_url": plane_url,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Provision Plane project for ADR governance",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--plane-url",
        default=os.getenv("PLANE_URL", "http://10.10.10.20:8093/api/v1"),
        help="Plane API URL (default: from PLANE_URL env or http://10.10.10.20:8093/api/v1)",
    )
    parser.add_argument(
        "--workspace-slug",
        default=os.getenv("PLANE_WORKSPACE_SLUG", "default"),
        help="Plane workspace slug (default: from PLANE_WORKSPACE_SLUG env or 'default')",
    )
    parser.add_argument(
        "--admin-token",
        default=os.getenv("PLANE_ADMIN_TOKEN"),
        help="Plane admin token (required, default: from PLANE_ADMIN_TOKEN env)",
    )
    parser.add_argument(
        "--output-file",
        default=".local/plane.env",
        help="Output file for credentials (default: .local/plane.env)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be created without actually creating",
    )

    args = parser.parse_args()

    # Validate inputs
    if not args.admin_token:
        print("ERROR: PLANE_ADMIN_TOKEN not provided", file=sys.stderr)
        print("Set via: --admin-token or PLANE_ADMIN_TOKEN environment variable", file=sys.stderr)
        return 1

    if args.dry_run:
        print("[DRY-RUN] Would provision:")
        print(f"  Workspace: {args.workspace_slug}")
        print("  Project: adr-index (Architecture Decisions)")
        print("  API Token: (would create)")
        print(f"  Output: {args.output_file}")
        return 0

    try:
        result = provision_adr_project(
            plane_url=args.plane_url,
            admin_token=args.admin_token,
            workspace_slug=args.workspace_slug,
            output_file=args.output_file,
        )

        print("\n" + "=" * 60)
        print("[✓] ADR governance project provisioned successfully!")
        print("=" * 60)
        print("\nNext steps:")
        print(f"  1. Source the credentials: source {args.output_file}")
        print("  2. Sync ADRs to Plane: make sync-adrs-to-plane")
        print("  3. Verify in Plane: Check project 'Architecture Decisions'")
        print()

        return 0

    except Exception as e:
        print(f"\n[✗] Provisioning failed: {e}", file=sys.stderr)
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
