#!/usr/bin/env python3
"""Validate the generated TLS certificate declarations against platform catalogs.

ADR 0374 Phase 3 — TLS Certificate Management.

Loads inventory/group_vars/platform_tls_certs.yml (generated by
generate_cross_cutting_artifacts.py --write --only tls) and cross-checks it
against:
  - config/generated/dns-declarations.yaml  — every cert domain must have a DNS entry
  - config/subdomain-catalog.json           — provider consistency check
  - config/certificate-catalog.json         — coverage check (warns on catalog entries
                                              with no registry service)

Usage:
    python scripts/validate_tls_certs.py --check
    python scripts/validate_tls_certs.py --check --verbose
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import yaml  # noqa: E402 — must come after sys.path adjustment

REPO_ROOT = Path(__file__).resolve().parents[1]
TLS_CERTS_PATH = REPO_ROOT / "inventory" / "group_vars" / "platform_tls_certs.yml"
DNS_DECLARATIONS_PATH = REPO_ROOT / "config" / "generated" / "dns-declarations.yaml"
SUBDOMAIN_CATALOG_PATH = REPO_ROOT / "config" / "subdomain-catalog.json"
CERT_CATALOG_PATH = REPO_ROOT / "config" / "certificate-catalog.json"


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------


def _load_tls_certs() -> dict[str, dict]:
    """Load platform_tls_certs.yml. Raises SystemExit if missing."""
    if not TLS_CERTS_PATH.exists():
        print(
            f"ERROR: {TLS_CERTS_PATH.relative_to(REPO_ROOT)} not found.\n"
            "Run: python scripts/generate_cross_cutting_artifacts.py --write --only tls",
            file=sys.stderr,
        )
        sys.exit(1)
    with TLS_CERTS_PATH.open() as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        print(f"ERROR: {TLS_CERTS_PATH} did not parse as a mapping", file=sys.stderr)
        sys.exit(1)
    return data.get("platform_tls_certs", {})


def _load_dns_declarations() -> set[str]:
    """Return the set of FQDNs present in dns-declarations.yaml (if it exists)."""
    if not DNS_DECLARATIONS_PATH.exists():
        return set()
    with DNS_DECLARATIONS_PATH.open() as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        return set()
    fqdns: set[str] = set()
    for record in data.get("dns_declarations", []):
        if isinstance(record, dict) and "fqdn" in record:
            fqdns.add(record["fqdn"])
    return fqdns


def _load_subdomain_catalog() -> dict[str, dict]:
    """Return a mapping of fqdn -> subdomain entry from subdomain-catalog.json."""
    if not SUBDOMAIN_CATALOG_PATH.exists():
        return {}
    with SUBDOMAIN_CATALOG_PATH.open() as f:
        data = json.load(f)
    return {
        sd["fqdn"]: sd
        for sd in data.get("subdomains", [])
        if isinstance(sd, dict) and "fqdn" in sd
    }


def _load_cert_catalog() -> dict[str, dict]:
    """Return a mapping of host -> cert entry from certificate-catalog.json."""
    if not CERT_CATALOG_PATH.exists():
        return {}
    with CERT_CATALOG_PATH.open() as f:
        data = json.load(f)
    catalog: dict[str, dict] = {}
    for cert in data.get("certificates", []):
        if not isinstance(cert, dict):
            continue
        host = cert.get("endpoint", {}).get("host", "")
        if host:
            catalog[host] = cert
    return catalog


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------


def validate(verbose: bool = False) -> int:
    """Run all TLS validation checks. Returns number of errors found."""
    errors: list[str] = []
    warnings: list[str] = []

    # Load artifacts
    tls_certs = _load_tls_certs()
    dns_declared = _load_dns_declarations()
    subdomain_catalog = _load_subdomain_catalog()
    cert_catalog = _load_cert_catalog()

    if not tls_certs:
        print("WARNING: platform_tls_certs is empty. Did you run --write --only tls?")
        return 0

    print(f"Checking {len(tls_certs)} TLS certificate declaration(s) ...")

    # Track domains seen to detect duplicates within the generated file
    seen_domains: dict[str, str] = {}

    for fqdn, cert_entry in sorted(tls_certs.items()):
        service = cert_entry.get("service", "<unknown>")
        source = cert_entry.get("source", "")
        path = f"platform_tls_certs.{fqdn}"

        if verbose:
            print(f"  {fqdn} (service={service}, source={source})")

        # --- Duplicate domain check ---
        if fqdn in seen_domains:
            errors.append(
                f"{path}: duplicate domain — also claimed by '{seen_domains[fqdn]}'"
            )
        else:
            seen_domains[fqdn] = service

        # --- DNS declarations cross-check ---
        if dns_declared:
            if fqdn not in dns_declared:
                warnings.append(
                    f"{path}: domain '{fqdn}' has no entry in "
                    f"{DNS_DECLARATIONS_PATH.relative_to(REPO_ROOT)} "
                    "(DNS not yet generated for this domain)"
                )
        else:
            # dns-declarations.yaml doesn't exist yet (Phase 2 not run)
            if verbose:
                print(
                    f"  NOTE: {DNS_DECLARATIONS_PATH.relative_to(REPO_ROOT)} not found; "
                    "skipping DNS cross-check"
                )

        # --- Subdomain catalog provider consistency check ---
        if fqdn in subdomain_catalog:
            sd_entry = subdomain_catalog[fqdn]
            sd_tls = sd_entry.get("tls", {})
            sd_provider = sd_tls.get("provider", "")
            # Normalize: letsencrypt == letsencrypt, step-ca == step-ca
            if sd_provider and sd_provider != "none":
                # Map subdomain catalog provider names to registry cert_source names
                _provider_map = {
                    "letsencrypt": "letsencrypt",
                    "step-ca": "step-ca",
                    "openbao": "openbao",
                    "self-signed": "self-signed",
                    "none": "none",
                }
                expected = _provider_map.get(sd_provider, sd_provider)
                if source and source != expected:
                    warnings.append(
                        f"{path}: cert_source='{source}' but subdomain-catalog.json "
                        f"lists provider='{sd_provider}' for '{fqdn}'"
                    )

        # --- letsencrypt on internal domains ---
        if source == "letsencrypt" and (
            ".internal" in fqdn or fqdn.endswith(".local")
        ):
            errors.append(
                f"{path}: cert_source=letsencrypt declared for domain '{fqdn}' "
                "which appears to be internal (.internal or .local). "
                "Use step-ca or self-signed for internal domains."
            )

    # --- Certificate catalog coverage check ---
    # Warn about cert catalog entries (with public FQDNs) that have no registry entry
    registered_domains = set(tls_certs.keys())
    for host, cert in cert_catalog.items():
        # Skip IP addresses
        if all(c.isdigit() or c == "." for c in host):
            continue
        status = cert.get("status", "")
        if status != "active":
            continue
        if host not in registered_domains:
            warnings.append(
                f"certificate-catalog.json has active entry for '{host}' "
                f"(service_id='{cert.get('service_id', '?')}') "
                "but no corresponding platform_tls_certs entry. "
                "Consider adding a tls section to the registry."
            )

    # --- Report ---
    if warnings:
        print(f"\n{len(warnings)} warning(s):")
        for w in warnings:
            print(f"  WARN: {w}")

    if errors:
        print(f"\n{len(errors)} error(s):", file=sys.stderr)
        for e in errors:
            print(f"  ERROR: {e}", file=sys.stderr)
    else:
        print(f"\nAll {len(tls_certs)} TLS cert declarations are valid.")

    return len(errors)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate platform TLS certificate declarations — ADR 0374 Phase 3.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        required=True,
        help="Run validation checks (required flag)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Print each domain as it is checked",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    error_count = validate(verbose=args.verbose)
    return 1 if error_count > 0 else 0


if __name__ == "__main__":
    sys.exit(main())
