#!/usr/bin/env python3
"""Validate service completeness.

# TODO: refine — auto-generated by heal_validator_docstrings.py
"""

from service_completeness import main


if __name__ == "__main__":
    raise SystemExit(main())
