#!/usr/bin/env python3
"""Validate service catalog.

# TODO: refine — auto-generated by heal_validator_docstrings.py
"""

from service_catalog import main


if __name__ == "__main__":
    raise SystemExit(main(["--validate"]))
