---
- name: Manage tailnet DNS name for PostgreSQL
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    database_dns_record_value: "{{ hostvars['proxmox_florin'].management_tailscale_ipv4 }}"

  roles:
    - role: hetzner_dns_record
      vars:
        hetzner_dns_record_zone_name: "{{ database_dns_zone_name }}"
        hetzner_dns_record_name: "{{ database_dns_record_name }}"
        hetzner_dns_record_type: "{{ database_dns_record_type }}"
        hetzner_dns_record_value: "{{ database_dns_record_value }}"
        hetzner_dns_record_ttl: "{{ database_dns_record_ttl }}"
